
mpi_vgs.o:     file format elf32-littlearm

SYMBOL TABLE:
00000000 l    df *ABS*	00000000 mpi_vgs.c
00000000 l    d  .text	00000000 .text
00000000 l    d  .data	00000000 .data
00000000 l    d  .bss	00000000 .bss
00000000 l    d  .text.vgs_check_open	00000000 .text.vgs_check_open
00000000 l     F .text.vgs_check_open	00000090 vgs_check_open
00000000 l       .rodata.vgs_check_open.str1.4	00000000 .LC0
0000000c l       .rodata.vgs_check_open.str1.4	00000000 .LC1
00000000 l    d  .text.vgs_check_null_ptr.part.1	00000000 .text.vgs_check_null_ptr.part.1
00000000 l     F .text.vgs_check_null_ptr.part.1	00000048 vgs_check_null_ptr.part.1
00000000 l       .rodata.vgs_check_null_ptr.part.1.str1.4	00000000 .LC2
00000000 l    d  .text.hi_mpi_vgs_add_scale_task	00000000 .text.hi_mpi_vgs_add_scale_task
00000000 l     F .text.hi_mpi_vgs_add_scale_task	00000168 hi_mpi_vgs_add_scale_task
00000000 l       .rodata.hi_mpi_vgs_add_scale_task.str1.4	00000000 .LC3
00000000 l    d  .text.hi_mpi_vgs_add_draw_line_task	00000000 .text.hi_mpi_vgs_add_draw_line_task
00000000 l     F .text.hi_mpi_vgs_add_draw_line_task	00000100 hi_mpi_vgs_add_draw_line_task
00000000 l    d  .text.hi_mpi_vgs_add_cover_task	00000000 .text.hi_mpi_vgs_add_cover_task
00000000 l     F .text.hi_mpi_vgs_add_cover_task	00000100 hi_mpi_vgs_add_cover_task
00000000 l    d  .text.hi_mpi_vgs_add_osd_task	00000000 .text.hi_mpi_vgs_add_osd_task
00000000 l     F .text.hi_mpi_vgs_add_osd_task	00000100 hi_mpi_vgs_add_osd_task
00000000 l    d  .text.hi_mpi_vgs_add_draw_line_task_array	00000000 .text.hi_mpi_vgs_add_draw_line_task_array
00000000 l     F .text.hi_mpi_vgs_add_draw_line_task_array	000000fc hi_mpi_vgs_add_draw_line_task_array
00000000 l    d  .text.hi_mpi_vgs_add_cover_task_array	00000000 .text.hi_mpi_vgs_add_cover_task_array
00000000 l     F .text.hi_mpi_vgs_add_cover_task_array	000000fc hi_mpi_vgs_add_cover_task_array
00000000 l    d  .text.hi_mpi_vgs_add_osd_task_array	00000000 .text.hi_mpi_vgs_add_osd_task_array
00000000 l     F .text.hi_mpi_vgs_add_osd_task_array	000000fc hi_mpi_vgs_add_osd_task_array
00000000 l    d  .text.hi_mpi_vgs_add_rotation_task	00000000 .text.hi_mpi_vgs_add_rotation_task
00000000 l     F .text.hi_mpi_vgs_add_rotation_task	000000e0 hi_mpi_vgs_add_rotation_task
00000000 l    d  .text.hi_mpi_vgs_add_luma_task_array	00000000 .text.hi_mpi_vgs_add_luma_task_array
00000000 l     F .text.hi_mpi_vgs_add_luma_task_array	00000120 hi_mpi_vgs_add_luma_task_array
00000000 l    d  .text.HI_MPI_VGS_BeginJob	00000000 .text.HI_MPI_VGS_BeginJob
00000000 l    d  .text.HI_MPI_VGS_EndJob	00000000 .text.HI_MPI_VGS_EndJob
00000000 l    d  .text.HI_MPI_VGS_CancelJob	00000000 .text.HI_MPI_VGS_CancelJob
00000000 l    d  .text.HI_MPI_VGS_AddScaleTask	00000000 .text.HI_MPI_VGS_AddScaleTask
00000000 l    d  .text.HI_MPI_VGS_AddDrawLineTask	00000000 .text.HI_MPI_VGS_AddDrawLineTask
00000000 l    d  .text.HI_MPI_VGS_AddCoverTask	00000000 .text.HI_MPI_VGS_AddCoverTask
00000000 l    d  .text.HI_MPI_VGS_AddOsdTask	00000000 .text.HI_MPI_VGS_AddOsdTask
00000000 l    d  .text.HI_MPI_VGS_AddDrawLineTaskArray	00000000 .text.HI_MPI_VGS_AddDrawLineTaskArray
00000000 l    d  .text.HI_MPI_VGS_AddCoverTaskArray	00000000 .text.HI_MPI_VGS_AddCoverTaskArray
00000000 l    d  .text.HI_MPI_VGS_AddOsdTaskArray	00000000 .text.HI_MPI_VGS_AddOsdTaskArray
00000000 l    d  .text.HI_MPI_VGS_AddRotationTask	00000000 .text.HI_MPI_VGS_AddRotationTask
00000000 l    d  .text.HI_MPI_VGS_AddLumaTaskArray	00000000 .text.HI_MPI_VGS_AddLumaTaskArray
00000000 l    d  .bss.g_vgs_mutex	00000000 .bss.g_vgs_mutex
00000000 l     O .bss.g_vgs_mutex	00000018 g_vgs_mutex
00000000 l    d  .data.g_device_id	00000000 .data.g_device_id
00000000 l     O .data.g_device_id	00000004 g_device_id
00000000 l    d  .rodata.__FUNCTION__.10776	00000000 .rodata.__FUNCTION__.10776
00000000 l     O .rodata.__FUNCTION__.10776	00000013 __FUNCTION__.10776
00000000 l    d  .rodata.__FUNCTION__.10798	00000000 .rodata.__FUNCTION__.10798
00000000 l     O .rodata.__FUNCTION__.10798	0000001a __FUNCTION__.10798
00000000 l    d  .rodata.hi_mpi_vgs_add_scale_task.str1.4	00000000 .rodata.hi_mpi_vgs_add_scale_task.str1.4
00000000 l    d  .rodata.vgs_check_null_ptr.part.1.str1.4	00000000 .rodata.vgs_check_null_ptr.part.1.str1.4
00000000 l    d  .rodata.vgs_check_open.str1.4	00000000 .rodata.vgs_check_open.str1.4
00000000 l    d  .note.GNU-stack	00000000 .note.GNU-stack
00000000 l    d  .comment	00000000 .comment
00000000 l    d  .ARM.attributes	00000000 .ARM.attributes
00000000         *UND*	00000000 pthread_mutex_lock
00000000         *UND*	00000000 pthread_mutex_unlock
00000000         *UND*	00000000 open
00000000         *UND*	00000000 puts
00000000         *UND*	00000000 fprintf
00000000         *UND*	00000000 _GLOBAL_OFFSET_TABLE_
00000000         *UND*	00000000 stderr
00000000         *UND*	00000000 memcpy_s
00000000         *UND*	00000000 ioctl
00000000         *UND*	00000000 __stack_chk_fail
00000000         *UND*	00000000 __stack_chk_guard
00000000 g     F .text.HI_MPI_VGS_BeginJob	00000064 HI_MPI_VGS_BeginJob
00000000 g     F .text.HI_MPI_VGS_EndJob	00000098 HI_MPI_VGS_EndJob
00000000 g     F .text.HI_MPI_VGS_CancelJob	00000098 HI_MPI_VGS_CancelJob
00000000 g     F .text.HI_MPI_VGS_AddScaleTask	00000004 HI_MPI_VGS_AddScaleTask
00000000 g     F .text.HI_MPI_VGS_AddDrawLineTask	00000004 HI_MPI_VGS_AddDrawLineTask
00000000 g     F .text.HI_MPI_VGS_AddCoverTask	00000004 HI_MPI_VGS_AddCoverTask
00000000 g     F .text.HI_MPI_VGS_AddOsdTask	00000004 HI_MPI_VGS_AddOsdTask
00000000 g     F .text.HI_MPI_VGS_AddDrawLineTaskArray	00000004 HI_MPI_VGS_AddDrawLineTaskArray
00000000 g     F .text.HI_MPI_VGS_AddCoverTaskArray	00000004 HI_MPI_VGS_AddCoverTaskArray
00000000 g     F .text.HI_MPI_VGS_AddOsdTaskArray	00000004 HI_MPI_VGS_AddOsdTaskArray
00000000 g     F .text.HI_MPI_VGS_AddRotationTask	00000004 HI_MPI_VGS_AddRotationTask
00000000 g     F .text.HI_MPI_VGS_AddLumaTaskArray	00000004 HI_MPI_VGS_AddLumaTaskArray



Disassembly of section .text.vgs_check_open:

00000000 <vgs_check_open>:
   0:	e92d4070 	push	{r4, r5, r6, lr}
   4:	e59f5070 	ldr	r5, [pc, #112]	; 7c <vgs_check_open+0x7c>
   8:	e59f4070 	ldr	r4, [pc, #112]	; 80 <vgs_check_open+0x80>
   c:	e08f5005 	add	r5, pc, r5
  10:	e08f4004 	add	r4, pc, r4
  14:	e1a00005 	mov	r0, r5
  18:	ebfffffe 	bl	0 <pthread_mutex_lock>
			18: R_ARM_CALL	pthread_mutex_lock
  1c:	e5943000 	ldr	r3, [r4]
  20:	e3530000 	cmp	r3, #0
  24:	ba000004 	blt	3c <vgs_check_open+0x3c>
  28:	e59f0054 	ldr	r0, [pc, #84]	; 84 <vgs_check_open+0x84>
  2c:	e08f0000 	add	r0, pc, r0
  30:	ebfffffe 	bl	0 <pthread_mutex_unlock>
			30: R_ARM_CALL	pthread_mutex_unlock
  34:	e3a00000 	mov	r0, #0
  38:	e8bd8070 	pop	{r4, r5, r6, pc}
  3c:	e59f0044 	ldr	r0, [pc, #68]	; 88 <vgs_check_open+0x88>
  40:	e3a02000 	mov	r2, #0
  44:	e3a01002 	mov	r1, #2
  48:	e08f0000 	add	r0, pc, r0
  4c:	ebfffffe 	bl	0 <open>
			4c: R_ARM_CALL	open
  50:	e5840000 	str	r0, [r4]
  54:	e3500000 	cmp	r0, #0
  58:	aafffff2 	bge	28 <vgs_check_open+0x28>
  5c:	e1a00005 	mov	r0, r5
  60:	ebfffffe 	bl	0 <pthread_mutex_unlock>
			60: R_ARM_CALL	pthread_mutex_unlock
  64:	e59f0020 	ldr	r0, [pc, #32]	; 8c <vgs_check_open+0x8c>
  68:	e08f0000 	add	r0, pc, r0
  6c:	ebfffffe 	bl	0 <puts>
			6c: R_ARM_CALL	puts
  70:	e3080010 	movw	r0, #32784	; 0x8010
  74:	e34a002d 	movt	r0, #41005	; 0xa02d
  78:	e8bd8070 	pop	{r4, r5, r6, pc}
  7c:	00000068 	.word	0x00000068
			7c: R_ARM_REL32	.bss.g_vgs_mutex
  80:	00000068 	.word	0x00000068
			80: R_ARM_REL32	.data.g_device_id
  84:	00000050 	.word	0x00000050
			84: R_ARM_REL32	.bss.g_vgs_mutex
  88:	00000038 	.word	0x00000038
			88: R_ARM_REL32	.LC0
  8c:	0000001c 	.word	0x0000001c
			8c: R_ARM_REL32	.LC1

Disassembly of section .text.vgs_check_null_ptr.part.1:

00000000 <vgs_check_null_ptr.part.1>:
   0:	e59f1030 	ldr	r1, [pc, #48]	; 38 <vgs_check_null_ptr.part.1+0x38>
   4:	e59f3030 	ldr	r3, [pc, #48]	; 3c <vgs_check_null_ptr.part.1+0x3c>
   8:	e08f1001 	add	r1, pc, r1
   c:	e92d4010 	push	{r4, lr}
  10:	e59f2028 	ldr	r2, [pc, #40]	; 40 <vgs_check_null_ptr.part.1+0x40>
  14:	e7913003 	ldr	r3, [r1, r3]
  18:	e59f1024 	ldr	r1, [pc, #36]	; 44 <vgs_check_null_ptr.part.1+0x44>
  1c:	e08f2002 	add	r2, pc, r2
  20:	e08f1001 	add	r1, pc, r1
  24:	e5930000 	ldr	r0, [r3]
  28:	ebfffffe 	bl	0 <fprintf>
			28: R_ARM_CALL	fprintf
  2c:	e3080006 	movw	r0, #32774	; 0x8006
  30:	e34a002d 	movt	r0, #41005	; 0xa02d
  34:	e8bd8010 	pop	{r4, pc}
  38:	00000028 	.word	0x00000028
			38: R_ARM_GOTPC	_GLOBAL_OFFSET_TABLE_
  3c:	00000000 	.word	0x00000000
			3c: R_ARM_GOT32	stderr
  40:	0000001c 	.word	0x0000001c
			40: R_ARM_REL32	.rodata.__FUNCTION__.10776
  44:	0000001c 	.word	0x0000001c
			44: R_ARM_REL32	.LC2

Disassembly of section .text.hi_mpi_vgs_add_scale_task:

00000000 <hi_mpi_vgs_add_scale_task>:
   0:	e92d40f0 	push	{r4, r5, r6, r7, lr}
   4:	e1a04002 	mov	r4, r2
   8:	e59f2138 	ldr	r2, [pc, #312]	; 148 <hi_mpi_vgs_add_scale_task+0x148>
   c:	e24ddfb9 	sub	sp, sp, #740	; 0x2e4
  10:	e59f3134 	ldr	r3, [pc, #308]	; 14c <hi_mpi_vgs_add_scale_task+0x14c>
  14:	e1a07000 	mov	r7, r0
  18:	e08f2002 	add	r2, pc, r2
  1c:	e1a05001 	mov	r5, r1
  20:	e59f6128 	ldr	r6, [pc, #296]	; 150 <hi_mpi_vgs_add_scale_task+0x150>
  24:	e7923003 	ldr	r3, [r2, r3]
  28:	e08f6006 	add	r6, pc, r6
  2c:	e5933000 	ldr	r3, [r3]
  30:	e58d32dc 	str	r3, [sp, #732]	; 0x2dc
  34:	e3a03000 	mov	r3, #0
  38:	ebfffffe 	bl	0 <hi_mpi_vgs_add_scale_task>
			38: R_ARM_CALL	vgs_check_open
  3c:	e3500000 	cmp	r0, #0
  40:	1a00003c 	bne	138 <hi_mpi_vgs_add_scale_task+0x138>
  44:	e3550000 	cmp	r5, #0
  48:	0a000034 	beq	120 <hi_mpi_vgs_add_scale_task+0x120>
  4c:	e58d7000 	str	r7, [sp]
  50:	e3540004 	cmp	r4, #4
  54:	908ff104 	addls	pc, pc, r4, lsl #2
  58:	ea000024 	b	f0 <hi_mpi_vgs_add_scale_task+0xf0>
  5c:	ea00001a 	b	cc <hi_mpi_vgs_add_scale_task+0xcc>
  60:	ea000022 	b	f0 <hi_mpi_vgs_add_scale_task+0xf0>
  64:	ea00001b 	b	d8 <hi_mpi_vgs_add_scale_task+0xd8>
  68:	ea00001d 	b	e4 <hi_mpi_vgs_add_scale_task+0xe4>
  6c:	eaffffff 	b	70 <hi_mpi_vgs_add_scale_task+0x70>
  70:	e3a03004 	mov	r3, #4
  74:	e58d32d0 	str	r3, [sp, #720]	; 0x2d0
  78:	e3a03fb2 	mov	r3, #712	; 0x2c8
  7c:	e1a02005 	mov	r2, r5
  80:	e1a01003 	mov	r1, r3
  84:	e28d0008 	add	r0, sp, #8
  88:	ebfffffe 	bl	0 <memcpy_s>
			88: R_ARM_CALL	memcpy_s
  8c:	e59f30c0 	ldr	r3, [pc, #192]	; 154 <hi_mpi_vgs_add_scale_task+0x154>
  90:	e3041a03 	movw	r1, #18947	; 0x4a03
  94:	e34412d8 	movt	r1, #17112	; 0x42d8
  98:	e1a0200d 	mov	r2, sp
  9c:	e79f0003 	ldr	r0, [pc, r3]
  a0:	ebfffffe 	bl	0 <ioctl>
			a0: R_ARM_CALL	ioctl
  a4:	e59f20ac 	ldr	r2, [pc, #172]	; 158 <hi_mpi_vgs_add_scale_task+0x158>
  a8:	e59f309c 	ldr	r3, [pc, #156]	; 14c <hi_mpi_vgs_add_scale_task+0x14c>
  ac:	e08f2002 	add	r2, pc, r2
  b0:	e7923003 	ldr	r3, [r2, r3]
  b4:	e5932000 	ldr	r2, [r3]
  b8:	e59d32dc 	ldr	r3, [sp, #732]	; 0x2dc
  bc:	e0332002 	eors	r2, r3, r2
  c0:	1a00001f 	bne	144 <hi_mpi_vgs_add_scale_task+0x144>
  c4:	e28ddfb9 	add	sp, sp, #740	; 0x2e4
  c8:	e8bd80f0 	pop	{r4, r5, r6, r7, pc}
  cc:	e3a03000 	mov	r3, #0
  d0:	e58d32d0 	str	r3, [sp, #720]	; 0x2d0
  d4:	eaffffe7 	b	78 <hi_mpi_vgs_add_scale_task+0x78>
  d8:	e3a03002 	mov	r3, #2
  dc:	e58d32d0 	str	r3, [sp, #720]	; 0x2d0
  e0:	eaffffe4 	b	78 <hi_mpi_vgs_add_scale_task+0x78>
  e4:	e3a03003 	mov	r3, #3
  e8:	e58d32d0 	str	r3, [sp, #720]	; 0x2d0
  ec:	eaffffe1 	b	78 <hi_mpi_vgs_add_scale_task+0x78>
  f0:	e59f1064 	ldr	r1, [pc, #100]	; 15c <hi_mpi_vgs_add_scale_task+0x15c>
  f4:	e1a03004 	mov	r3, r4
  f8:	e59f2060 	ldr	r2, [pc, #96]	; 160 <hi_mpi_vgs_add_scale_task+0x160>
  fc:	e7960001 	ldr	r0, [r6, r1]
 100:	e59f105c 	ldr	r1, [pc, #92]	; 164 <hi_mpi_vgs_add_scale_task+0x164>
 104:	e08f2002 	add	r2, pc, r2
 108:	e08f1001 	add	r1, pc, r1
 10c:	e5900000 	ldr	r0, [r0]
 110:	ebfffffe 	bl	0 <fprintf>
			110: R_ARM_CALL	fprintf
 114:	e3080003 	movw	r0, #32771	; 0x8003
 118:	e34a002d 	movt	r0, #41005	; 0xa02d
 11c:	eaffffe0 	b	a4 <hi_mpi_vgs_add_scale_task+0xa4>
 120:	ebfffffe 	bl	0 <hi_mpi_vgs_add_scale_task>
			120: R_ARM_CALL	vgs_check_null_ptr.part.1
 124:	e3500000 	cmp	r0, #0
 128:	13080006 	movwne	r0, #32774	; 0x8006
 12c:	134a002d 	movtne	r0, #41005	; 0xa02d
 130:	1affffdb 	bne	a4 <hi_mpi_vgs_add_scale_task+0xa4>
 134:	eaffffc4 	b	4c <hi_mpi_vgs_add_scale_task+0x4c>
 138:	e3080010 	movw	r0, #32784	; 0x8010
 13c:	e34a002d 	movt	r0, #41005	; 0xa02d
 140:	eaffffd7 	b	a4 <hi_mpi_vgs_add_scale_task+0xa4>
 144:	ebfffffe 	bl	0 <__stack_chk_fail>
			144: R_ARM_CALL	__stack_chk_fail
 148:	00000128 	.word	0x00000128
			148: R_ARM_GOTPC	_GLOBAL_OFFSET_TABLE_
 14c:	00000000 	.word	0x00000000
			14c: R_ARM_GOT32	__stack_chk_guard
 150:	00000120 	.word	0x00000120
			150: R_ARM_GOTPC	_GLOBAL_OFFSET_TABLE_
 154:	000000b0 	.word	0x000000b0
			154: R_ARM_REL32	.data.g_device_id
 158:	000000a4 	.word	0x000000a4
			158: R_ARM_GOTPC	_GLOBAL_OFFSET_TABLE_
 15c:	00000000 	.word	0x00000000
			15c: R_ARM_GOT32	stderr
 160:	00000054 	.word	0x00000054
			160: R_ARM_REL32	.rodata.__FUNCTION__.10798
 164:	00000054 	.word	0x00000054
			164: R_ARM_REL32	.LC3

Disassembly of section .text.hi_mpi_vgs_add_draw_line_task:

00000000 <hi_mpi_vgs_add_draw_line_task>:
   0:	e92d40f0 	push	{r4, r5, r6, r7, lr}
   4:	e1a06002 	mov	r6, r2
   8:	e59f20e0 	ldr	r2, [pc, #224]	; f0 <hi_mpi_vgs_add_draw_line_task+0xf0>
   c:	e24ddfb9 	sub	sp, sp, #740	; 0x2e4
  10:	e59f30dc 	ldr	r3, [pc, #220]	; f4 <hi_mpi_vgs_add_draw_line_task+0xf4>
  14:	e1a07000 	mov	r7, r0
  18:	e08f2002 	add	r2, pc, r2
  1c:	e1a05001 	mov	r5, r1
  20:	e7923003 	ldr	r3, [r2, r3]
  24:	e5933000 	ldr	r3, [r3]
  28:	e58d32dc 	str	r3, [sp, #732]	; 0x2dc
  2c:	e3a03000 	mov	r3, #0
  30:	ebfffffe 	bl	0 <hi_mpi_vgs_add_draw_line_task>
			30: R_ARM_CALL	vgs_check_open
  34:	e3500000 	cmp	r0, #0
  38:	1a000028 	bne	e0 <hi_mpi_vgs_add_draw_line_task+0xe0>
  3c:	e3550000 	cmp	r5, #0
  40:	0a00001c 	beq	b8 <hi_mpi_vgs_add_draw_line_task+0xb8>
  44:	e3560000 	cmp	r6, #0
  48:	0a000020 	beq	d0 <hi_mpi_vgs_add_draw_line_task+0xd0>
  4c:	e3a03fb2 	mov	r3, #712	; 0x2c8
  50:	e28d4e2e 	add	r4, sp, #736	; 0x2e0
  54:	e1a01003 	mov	r1, r3
  58:	e1a02005 	mov	r2, r5
  5c:	e52472e0 	str	r7, [r4, #-736]!	; 0xfffffd20
  60:	e28d0008 	add	r0, sp, #8
  64:	ebfffffe 	bl	0 <memcpy_s>
			64: R_ARM_CALL	memcpy_s
  68:	e59f3088 	ldr	r3, [pc, #136]	; f8 <hi_mpi_vgs_add_draw_line_task+0xf8>
  6c:	e3041a04 	movw	r1, #18948	; 0x4a04
  70:	e34412d8 	movt	r1, #17112	; 0x42d8
  74:	e1a02004 	mov	r2, r4
  78:	e08f3003 	add	r3, pc, r3
  7c:	e58d62d4 	str	r6, [sp, #724]	; 0x2d4
  80:	e5930000 	ldr	r0, [r3]
  84:	e3a03001 	mov	r3, #1
  88:	e58d32d0 	str	r3, [sp, #720]	; 0x2d0
  8c:	ebfffffe 	bl	0 <ioctl>
			8c: R_ARM_CALL	ioctl
  90:	e59f2064 	ldr	r2, [pc, #100]	; fc <hi_mpi_vgs_add_draw_line_task+0xfc>
  94:	e59f3058 	ldr	r3, [pc, #88]	; f4 <hi_mpi_vgs_add_draw_line_task+0xf4>
  98:	e08f2002 	add	r2, pc, r2
  9c:	e7923003 	ldr	r3, [r2, r3]
  a0:	e5932000 	ldr	r2, [r3]
  a4:	e59d32dc 	ldr	r3, [sp, #732]	; 0x2dc
  a8:	e0332002 	eors	r2, r3, r2
  ac:	1a00000e 	bne	ec <hi_mpi_vgs_add_draw_line_task+0xec>
  b0:	e28ddfb9 	add	sp, sp, #740	; 0x2e4
  b4:	e8bd80f0 	pop	{r4, r5, r6, r7, pc}
  b8:	ebfffffe 	bl	0 <hi_mpi_vgs_add_draw_line_task>
			b8: R_ARM_CALL	vgs_check_null_ptr.part.1
  bc:	e3500000 	cmp	r0, #0
  c0:	0affffdf 	beq	44 <hi_mpi_vgs_add_draw_line_task+0x44>
  c4:	e3080006 	movw	r0, #32774	; 0x8006
  c8:	e34a002d 	movt	r0, #41005	; 0xa02d
  cc:	eaffffef 	b	90 <hi_mpi_vgs_add_draw_line_task+0x90>
  d0:	ebfffffe 	bl	0 <hi_mpi_vgs_add_draw_line_task>
			d0: R_ARM_CALL	vgs_check_null_ptr.part.1
  d4:	e3500000 	cmp	r0, #0
  d8:	1afffff9 	bne	c4 <hi_mpi_vgs_add_draw_line_task+0xc4>
  dc:	eaffffda 	b	4c <hi_mpi_vgs_add_draw_line_task+0x4c>
  e0:	e3080010 	movw	r0, #32784	; 0x8010
  e4:	e34a002d 	movt	r0, #41005	; 0xa02d
  e8:	eaffffe8 	b	90 <hi_mpi_vgs_add_draw_line_task+0x90>
  ec:	ebfffffe 	bl	0 <__stack_chk_fail>
			ec: R_ARM_CALL	__stack_chk_fail
  f0:	000000d0 	.word	0x000000d0
			f0: R_ARM_GOTPC	_GLOBAL_OFFSET_TABLE_
  f4:	00000000 	.word	0x00000000
			f4: R_ARM_GOT32	__stack_chk_guard
  f8:	00000078 	.word	0x00000078
			f8: R_ARM_REL32	.data.g_device_id
  fc:	0000005c 	.word	0x0000005c
			fc: R_ARM_GOTPC	_GLOBAL_OFFSET_TABLE_

Disassembly of section .text.hi_mpi_vgs_add_cover_task:

00000000 <hi_mpi_vgs_add_cover_task>:
   0:	e92d40f0 	push	{r4, r5, r6, r7, lr}
   4:	e1a06002 	mov	r6, r2
   8:	e59f20e0 	ldr	r2, [pc, #224]	; f0 <hi_mpi_vgs_add_cover_task+0xf0>
   c:	e24ddfb9 	sub	sp, sp, #740	; 0x2e4
  10:	e59f30dc 	ldr	r3, [pc, #220]	; f4 <hi_mpi_vgs_add_cover_task+0xf4>
  14:	e1a07000 	mov	r7, r0
  18:	e08f2002 	add	r2, pc, r2
  1c:	e1a05001 	mov	r5, r1
  20:	e7923003 	ldr	r3, [r2, r3]
  24:	e5933000 	ldr	r3, [r3]
  28:	e58d32dc 	str	r3, [sp, #732]	; 0x2dc
  2c:	e3a03000 	mov	r3, #0
  30:	ebfffffe 	bl	0 <hi_mpi_vgs_add_cover_task>
			30: R_ARM_CALL	vgs_check_open
  34:	e3500000 	cmp	r0, #0
  38:	1a000028 	bne	e0 <hi_mpi_vgs_add_cover_task+0xe0>
  3c:	e3550000 	cmp	r5, #0
  40:	0a00001c 	beq	b8 <hi_mpi_vgs_add_cover_task+0xb8>
  44:	e3560000 	cmp	r6, #0
  48:	0a000020 	beq	d0 <hi_mpi_vgs_add_cover_task+0xd0>
  4c:	e3a03fb2 	mov	r3, #712	; 0x2c8
  50:	e28d4e2e 	add	r4, sp, #736	; 0x2e0
  54:	e1a01003 	mov	r1, r3
  58:	e1a02005 	mov	r2, r5
  5c:	e52472e0 	str	r7, [r4, #-736]!	; 0xfffffd20
  60:	e28d0008 	add	r0, sp, #8
  64:	ebfffffe 	bl	0 <memcpy_s>
			64: R_ARM_CALL	memcpy_s
  68:	e59f3088 	ldr	r3, [pc, #136]	; f8 <hi_mpi_vgs_add_cover_task+0xf8>
  6c:	e3041a05 	movw	r1, #18949	; 0x4a05
  70:	e34412d8 	movt	r1, #17112	; 0x42d8
  74:	e1a02004 	mov	r2, r4
  78:	e08f3003 	add	r3, pc, r3
  7c:	e58d62d4 	str	r6, [sp, #724]	; 0x2d4
  80:	e5930000 	ldr	r0, [r3]
  84:	e3a03001 	mov	r3, #1
  88:	e58d32d0 	str	r3, [sp, #720]	; 0x2d0
  8c:	ebfffffe 	bl	0 <ioctl>
			8c: R_ARM_CALL	ioctl
  90:	e59f2064 	ldr	r2, [pc, #100]	; fc <hi_mpi_vgs_add_cover_task+0xfc>
  94:	e59f3058 	ldr	r3, [pc, #88]	; f4 <hi_mpi_vgs_add_cover_task+0xf4>
  98:	e08f2002 	add	r2, pc, r2
  9c:	e7923003 	ldr	r3, [r2, r3]
  a0:	e5932000 	ldr	r2, [r3]
  a4:	e59d32dc 	ldr	r3, [sp, #732]	; 0x2dc
  a8:	e0332002 	eors	r2, r3, r2
  ac:	1a00000e 	bne	ec <hi_mpi_vgs_add_cover_task+0xec>
  b0:	e28ddfb9 	add	sp, sp, #740	; 0x2e4
  b4:	e8bd80f0 	pop	{r4, r5, r6, r7, pc}
  b8:	ebfffffe 	bl	0 <hi_mpi_vgs_add_cover_task>
			b8: R_ARM_CALL	vgs_check_null_ptr.part.1
  bc:	e3500000 	cmp	r0, #0
  c0:	0affffdf 	beq	44 <hi_mpi_vgs_add_cover_task+0x44>
  c4:	e3080006 	movw	r0, #32774	; 0x8006
  c8:	e34a002d 	movt	r0, #41005	; 0xa02d
  cc:	eaffffef 	b	90 <hi_mpi_vgs_add_cover_task+0x90>
  d0:	ebfffffe 	bl	0 <hi_mpi_vgs_add_cover_task>
			d0: R_ARM_CALL	vgs_check_null_ptr.part.1
  d4:	e3500000 	cmp	r0, #0
  d8:	1afffff9 	bne	c4 <hi_mpi_vgs_add_cover_task+0xc4>
  dc:	eaffffda 	b	4c <hi_mpi_vgs_add_cover_task+0x4c>
  e0:	e3080010 	movw	r0, #32784	; 0x8010
  e4:	e34a002d 	movt	r0, #41005	; 0xa02d
  e8:	eaffffe8 	b	90 <hi_mpi_vgs_add_cover_task+0x90>
  ec:	ebfffffe 	bl	0 <__stack_chk_fail>
			ec: R_ARM_CALL	__stack_chk_fail
  f0:	000000d0 	.word	0x000000d0
			f0: R_ARM_GOTPC	_GLOBAL_OFFSET_TABLE_
  f4:	00000000 	.word	0x00000000
			f4: R_ARM_GOT32	__stack_chk_guard
  f8:	00000078 	.word	0x00000078
			f8: R_ARM_REL32	.data.g_device_id
  fc:	0000005c 	.word	0x0000005c
			fc: R_ARM_GOTPC	_GLOBAL_OFFSET_TABLE_

Disassembly of section .text.hi_mpi_vgs_add_osd_task:

00000000 <hi_mpi_vgs_add_osd_task>:
   0:	e92d40f0 	push	{r4, r5, r6, r7, lr}
   4:	e1a06002 	mov	r6, r2
   8:	e59f20e0 	ldr	r2, [pc, #224]	; f0 <hi_mpi_vgs_add_osd_task+0xf0>
   c:	e24ddfb9 	sub	sp, sp, #740	; 0x2e4
  10:	e59f30dc 	ldr	r3, [pc, #220]	; f4 <hi_mpi_vgs_add_osd_task+0xf4>
  14:	e1a07000 	mov	r7, r0
  18:	e08f2002 	add	r2, pc, r2
  1c:	e1a05001 	mov	r5, r1
  20:	e7923003 	ldr	r3, [r2, r3]
  24:	e5933000 	ldr	r3, [r3]
  28:	e58d32dc 	str	r3, [sp, #732]	; 0x2dc
  2c:	e3a03000 	mov	r3, #0
  30:	ebfffffe 	bl	0 <hi_mpi_vgs_add_osd_task>
			30: R_ARM_CALL	vgs_check_open
  34:	e3500000 	cmp	r0, #0
  38:	1a000028 	bne	e0 <hi_mpi_vgs_add_osd_task+0xe0>
  3c:	e3550000 	cmp	r5, #0
  40:	0a00001c 	beq	b8 <hi_mpi_vgs_add_osd_task+0xb8>
  44:	e3560000 	cmp	r6, #0
  48:	0a000020 	beq	d0 <hi_mpi_vgs_add_osd_task+0xd0>
  4c:	e3a03fb2 	mov	r3, #712	; 0x2c8
  50:	e28d4e2e 	add	r4, sp, #736	; 0x2e0
  54:	e1a01003 	mov	r1, r3
  58:	e1a02005 	mov	r2, r5
  5c:	e52472e0 	str	r7, [r4, #-736]!	; 0xfffffd20
  60:	e28d0008 	add	r0, sp, #8
  64:	ebfffffe 	bl	0 <memcpy_s>
			64: R_ARM_CALL	memcpy_s
  68:	e59f3088 	ldr	r3, [pc, #136]	; f8 <hi_mpi_vgs_add_osd_task+0xf8>
  6c:	e3041a06 	movw	r1, #18950	; 0x4a06
  70:	e34412d8 	movt	r1, #17112	; 0x42d8
  74:	e1a02004 	mov	r2, r4
  78:	e08f3003 	add	r3, pc, r3
  7c:	e58d62d4 	str	r6, [sp, #724]	; 0x2d4
  80:	e5930000 	ldr	r0, [r3]
  84:	e3a03001 	mov	r3, #1
  88:	e58d32d0 	str	r3, [sp, #720]	; 0x2d0
  8c:	ebfffffe 	bl	0 <ioctl>
			8c: R_ARM_CALL	ioctl
  90:	e59f2064 	ldr	r2, [pc, #100]	; fc <hi_mpi_vgs_add_osd_task+0xfc>
  94:	e59f3058 	ldr	r3, [pc, #88]	; f4 <hi_mpi_vgs_add_osd_task+0xf4>
  98:	e08f2002 	add	r2, pc, r2
  9c:	e7923003 	ldr	r3, [r2, r3]
  a0:	e5932000 	ldr	r2, [r3]
  a4:	e59d32dc 	ldr	r3, [sp, #732]	; 0x2dc
  a8:	e0332002 	eors	r2, r3, r2
  ac:	1a00000e 	bne	ec <hi_mpi_vgs_add_osd_task+0xec>
  b0:	e28ddfb9 	add	sp, sp, #740	; 0x2e4
  b4:	e8bd80f0 	pop	{r4, r5, r6, r7, pc}
  b8:	ebfffffe 	bl	0 <hi_mpi_vgs_add_osd_task>
			b8: R_ARM_CALL	vgs_check_null_ptr.part.1
  bc:	e3500000 	cmp	r0, #0
  c0:	0affffdf 	beq	44 <hi_mpi_vgs_add_osd_task+0x44>
  c4:	e3080006 	movw	r0, #32774	; 0x8006
  c8:	e34a002d 	movt	r0, #41005	; 0xa02d
  cc:	eaffffef 	b	90 <hi_mpi_vgs_add_osd_task+0x90>
  d0:	ebfffffe 	bl	0 <hi_mpi_vgs_add_osd_task>
			d0: R_ARM_CALL	vgs_check_null_ptr.part.1
  d4:	e3500000 	cmp	r0, #0
  d8:	1afffff9 	bne	c4 <hi_mpi_vgs_add_osd_task+0xc4>
  dc:	eaffffda 	b	4c <hi_mpi_vgs_add_osd_task+0x4c>
  e0:	e3080010 	movw	r0, #32784	; 0x8010
  e4:	e34a002d 	movt	r0, #41005	; 0xa02d
  e8:	eaffffe8 	b	90 <hi_mpi_vgs_add_osd_task+0x90>
  ec:	ebfffffe 	bl	0 <__stack_chk_fail>
			ec: R_ARM_CALL	__stack_chk_fail
  f0:	000000d0 	.word	0x000000d0
			f0: R_ARM_GOTPC	_GLOBAL_OFFSET_TABLE_
  f4:	00000000 	.word	0x00000000
			f4: R_ARM_GOT32	__stack_chk_guard
  f8:	00000078 	.word	0x00000078
			f8: R_ARM_REL32	.data.g_device_id
  fc:	0000005c 	.word	0x0000005c
			fc: R_ARM_GOTPC	_GLOBAL_OFFSET_TABLE_

Disassembly of section .text.hi_mpi_vgs_add_draw_line_task_array:

00000000 <hi_mpi_vgs_add_draw_line_task_array>:
   0:	e92d40f0 	push	{r4, r5, r6, r7, lr}
   4:	e1a05002 	mov	r5, r2
   8:	e59f20dc 	ldr	r2, [pc, #220]	; ec <hi_mpi_vgs_add_draw_line_task_array+0xec>
   c:	e1a07003 	mov	r7, r3
  10:	e59f30d8 	ldr	r3, [pc, #216]	; f0 <hi_mpi_vgs_add_draw_line_task_array+0xf0>
  14:	e24ddfb9 	sub	sp, sp, #740	; 0x2e4
  18:	e08f2002 	add	r2, pc, r2
  1c:	e1a06000 	mov	r6, r0
  20:	e1a04001 	mov	r4, r1
  24:	e7923003 	ldr	r3, [r2, r3]
  28:	e5933000 	ldr	r3, [r3]
  2c:	e58d32dc 	str	r3, [sp, #732]	; 0x2dc
  30:	e3a03000 	mov	r3, #0
  34:	ebfffffe 	bl	0 <hi_mpi_vgs_add_draw_line_task_array>
			34: R_ARM_CALL	vgs_check_open
  38:	e3500000 	cmp	r0, #0
  3c:	1a000026 	bne	dc <hi_mpi_vgs_add_draw_line_task_array+0xdc>
  40:	e3540000 	cmp	r4, #0
  44:	0a00001a 	beq	b4 <hi_mpi_vgs_add_draw_line_task_array+0xb4>
  48:	e3550000 	cmp	r5, #0
  4c:	0a00001e 	beq	cc <hi_mpi_vgs_add_draw_line_task_array+0xcc>
  50:	e58d6000 	str	r6, [sp]
  54:	e3a03fb2 	mov	r3, #712	; 0x2c8
  58:	e58d72d0 	str	r7, [sp, #720]	; 0x2d0
  5c:	e1a01003 	mov	r1, r3
  60:	e1a02004 	mov	r2, r4
  64:	e28d0008 	add	r0, sp, #8
  68:	ebfffffe 	bl	0 <memcpy_s>
			68: R_ARM_CALL	memcpy_s
  6c:	e59f3080 	ldr	r3, [pc, #128]	; f4 <hi_mpi_vgs_add_draw_line_task_array+0xf4>
  70:	e3041a07 	movw	r1, #18951	; 0x4a07
  74:	e34412d8 	movt	r1, #17112	; 0x42d8
  78:	e1a0200d 	mov	r2, sp
  7c:	e08f3003 	add	r3, pc, r3
  80:	e58d52d4 	str	r5, [sp, #724]	; 0x2d4
  84:	e5930000 	ldr	r0, [r3]
  88:	ebfffffe 	bl	0 <ioctl>
			88: R_ARM_CALL	ioctl
  8c:	e59f2064 	ldr	r2, [pc, #100]	; f8 <hi_mpi_vgs_add_draw_line_task_array+0xf8>
  90:	e59f3058 	ldr	r3, [pc, #88]	; f0 <hi_mpi_vgs_add_draw_line_task_array+0xf0>
  94:	e08f2002 	add	r2, pc, r2
  98:	e7923003 	ldr	r3, [r2, r3]
  9c:	e5932000 	ldr	r2, [r3]
  a0:	e59d32dc 	ldr	r3, [sp, #732]	; 0x2dc
  a4:	e0332002 	eors	r2, r3, r2
  a8:	1a00000e 	bne	e8 <hi_mpi_vgs_add_draw_line_task_array+0xe8>
  ac:	e28ddfb9 	add	sp, sp, #740	; 0x2e4
  b0:	e8bd80f0 	pop	{r4, r5, r6, r7, pc}
  b4:	ebfffffe 	bl	0 <hi_mpi_vgs_add_draw_line_task_array>
			b4: R_ARM_CALL	vgs_check_null_ptr.part.1
  b8:	e3500000 	cmp	r0, #0
  bc:	0affffe1 	beq	48 <hi_mpi_vgs_add_draw_line_task_array+0x48>
  c0:	e3080006 	movw	r0, #32774	; 0x8006
  c4:	e34a002d 	movt	r0, #41005	; 0xa02d
  c8:	eaffffef 	b	8c <hi_mpi_vgs_add_draw_line_task_array+0x8c>
  cc:	ebfffffe 	bl	0 <hi_mpi_vgs_add_draw_line_task_array>
			cc: R_ARM_CALL	vgs_check_null_ptr.part.1
  d0:	e3500000 	cmp	r0, #0
  d4:	1afffff9 	bne	c0 <hi_mpi_vgs_add_draw_line_task_array+0xc0>
  d8:	eaffffdc 	b	50 <hi_mpi_vgs_add_draw_line_task_array+0x50>
  dc:	e3080010 	movw	r0, #32784	; 0x8010
  e0:	e34a002d 	movt	r0, #41005	; 0xa02d
  e4:	eaffffe8 	b	8c <hi_mpi_vgs_add_draw_line_task_array+0x8c>
  e8:	ebfffffe 	bl	0 <__stack_chk_fail>
			e8: R_ARM_CALL	__stack_chk_fail
  ec:	000000cc 	.word	0x000000cc
			ec: R_ARM_GOTPC	_GLOBAL_OFFSET_TABLE_
  f0:	00000000 	.word	0x00000000
			f0: R_ARM_GOT32	__stack_chk_guard
  f4:	00000070 	.word	0x00000070
			f4: R_ARM_REL32	.data.g_device_id
  f8:	0000005c 	.word	0x0000005c
			f8: R_ARM_GOTPC	_GLOBAL_OFFSET_TABLE_

Disassembly of section .text.hi_mpi_vgs_add_cover_task_array:

00000000 <hi_mpi_vgs_add_cover_task_array>:
   0:	e92d40f0 	push	{r4, r5, r6, r7, lr}
   4:	e1a05002 	mov	r5, r2
   8:	e59f20dc 	ldr	r2, [pc, #220]	; ec <hi_mpi_vgs_add_cover_task_array+0xec>
   c:	e1a07003 	mov	r7, r3
  10:	e59f30d8 	ldr	r3, [pc, #216]	; f0 <hi_mpi_vgs_add_cover_task_array+0xf0>
  14:	e24ddfb9 	sub	sp, sp, #740	; 0x2e4
  18:	e08f2002 	add	r2, pc, r2
  1c:	e1a06000 	mov	r6, r0
  20:	e1a04001 	mov	r4, r1
  24:	e7923003 	ldr	r3, [r2, r3]
  28:	e5933000 	ldr	r3, [r3]
  2c:	e58d32dc 	str	r3, [sp, #732]	; 0x2dc
  30:	e3a03000 	mov	r3, #0
  34:	ebfffffe 	bl	0 <hi_mpi_vgs_add_cover_task_array>
			34: R_ARM_CALL	vgs_check_open
  38:	e3500000 	cmp	r0, #0
  3c:	1a000026 	bne	dc <hi_mpi_vgs_add_cover_task_array+0xdc>
  40:	e3540000 	cmp	r4, #0
  44:	0a00001a 	beq	b4 <hi_mpi_vgs_add_cover_task_array+0xb4>
  48:	e3550000 	cmp	r5, #0
  4c:	0a00001e 	beq	cc <hi_mpi_vgs_add_cover_task_array+0xcc>
  50:	e58d6000 	str	r6, [sp]
  54:	e3a03fb2 	mov	r3, #712	; 0x2c8
  58:	e58d72d0 	str	r7, [sp, #720]	; 0x2d0
  5c:	e1a01003 	mov	r1, r3
  60:	e1a02004 	mov	r2, r4
  64:	e28d0008 	add	r0, sp, #8
  68:	ebfffffe 	bl	0 <memcpy_s>
			68: R_ARM_CALL	memcpy_s
  6c:	e59f3080 	ldr	r3, [pc, #128]	; f4 <hi_mpi_vgs_add_cover_task_array+0xf4>
  70:	e3041a08 	movw	r1, #18952	; 0x4a08
  74:	e34412d8 	movt	r1, #17112	; 0x42d8
  78:	e1a0200d 	mov	r2, sp
  7c:	e08f3003 	add	r3, pc, r3
  80:	e58d52d4 	str	r5, [sp, #724]	; 0x2d4
  84:	e5930000 	ldr	r0, [r3]
  88:	ebfffffe 	bl	0 <ioctl>
			88: R_ARM_CALL	ioctl
  8c:	e59f2064 	ldr	r2, [pc, #100]	; f8 <hi_mpi_vgs_add_cover_task_array+0xf8>
  90:	e59f3058 	ldr	r3, [pc, #88]	; f0 <hi_mpi_vgs_add_cover_task_array+0xf0>
  94:	e08f2002 	add	r2, pc, r2
  98:	e7923003 	ldr	r3, [r2, r3]
  9c:	e5932000 	ldr	r2, [r3]
  a0:	e59d32dc 	ldr	r3, [sp, #732]	; 0x2dc
  a4:	e0332002 	eors	r2, r3, r2
  a8:	1a00000e 	bne	e8 <hi_mpi_vgs_add_cover_task_array+0xe8>
  ac:	e28ddfb9 	add	sp, sp, #740	; 0x2e4
  b0:	e8bd80f0 	pop	{r4, r5, r6, r7, pc}
  b4:	ebfffffe 	bl	0 <hi_mpi_vgs_add_cover_task_array>
			b4: R_ARM_CALL	vgs_check_null_ptr.part.1
  b8:	e3500000 	cmp	r0, #0
  bc:	0affffe1 	beq	48 <hi_mpi_vgs_add_cover_task_array+0x48>
  c0:	e3080006 	movw	r0, #32774	; 0x8006
  c4:	e34a002d 	movt	r0, #41005	; 0xa02d
  c8:	eaffffef 	b	8c <hi_mpi_vgs_add_cover_task_array+0x8c>
  cc:	ebfffffe 	bl	0 <hi_mpi_vgs_add_cover_task_array>
			cc: R_ARM_CALL	vgs_check_null_ptr.part.1
  d0:	e3500000 	cmp	r0, #0
  d4:	1afffff9 	bne	c0 <hi_mpi_vgs_add_cover_task_array+0xc0>
  d8:	eaffffdc 	b	50 <hi_mpi_vgs_add_cover_task_array+0x50>
  dc:	e3080010 	movw	r0, #32784	; 0x8010
  e0:	e34a002d 	movt	r0, #41005	; 0xa02d
  e4:	eaffffe8 	b	8c <hi_mpi_vgs_add_cover_task_array+0x8c>
  e8:	ebfffffe 	bl	0 <__stack_chk_fail>
			e8: R_ARM_CALL	__stack_chk_fail
  ec:	000000cc 	.word	0x000000cc
			ec: R_ARM_GOTPC	_GLOBAL_OFFSET_TABLE_
  f0:	00000000 	.word	0x00000000
			f0: R_ARM_GOT32	__stack_chk_guard
  f4:	00000070 	.word	0x00000070
			f4: R_ARM_REL32	.data.g_device_id
  f8:	0000005c 	.word	0x0000005c
			f8: R_ARM_GOTPC	_GLOBAL_OFFSET_TABLE_

Disassembly of section .text.hi_mpi_vgs_add_osd_task_array:

00000000 <hi_mpi_vgs_add_osd_task_array>:
   0:	e92d40f0 	push	{r4, r5, r6, r7, lr}
   4:	e1a05002 	mov	r5, r2
   8:	e59f20dc 	ldr	r2, [pc, #220]	; ec <hi_mpi_vgs_add_osd_task_array+0xec>
   c:	e1a07003 	mov	r7, r3
  10:	e59f30d8 	ldr	r3, [pc, #216]	; f0 <hi_mpi_vgs_add_osd_task_array+0xf0>
  14:	e24ddfb9 	sub	sp, sp, #740	; 0x2e4
  18:	e08f2002 	add	r2, pc, r2
  1c:	e1a06000 	mov	r6, r0
  20:	e1a04001 	mov	r4, r1
  24:	e7923003 	ldr	r3, [r2, r3]
  28:	e5933000 	ldr	r3, [r3]
  2c:	e58d32dc 	str	r3, [sp, #732]	; 0x2dc
  30:	e3a03000 	mov	r3, #0
  34:	ebfffffe 	bl	0 <hi_mpi_vgs_add_osd_task_array>
			34: R_ARM_CALL	vgs_check_open
  38:	e3500000 	cmp	r0, #0
  3c:	1a000026 	bne	dc <hi_mpi_vgs_add_osd_task_array+0xdc>
  40:	e3540000 	cmp	r4, #0
  44:	0a00001a 	beq	b4 <hi_mpi_vgs_add_osd_task_array+0xb4>
  48:	e3550000 	cmp	r5, #0
  4c:	0a00001e 	beq	cc <hi_mpi_vgs_add_osd_task_array+0xcc>
  50:	e58d6000 	str	r6, [sp]
  54:	e3a03fb2 	mov	r3, #712	; 0x2c8
  58:	e58d72d0 	str	r7, [sp, #720]	; 0x2d0
  5c:	e1a01003 	mov	r1, r3
  60:	e1a02004 	mov	r2, r4
  64:	e28d0008 	add	r0, sp, #8
  68:	ebfffffe 	bl	0 <memcpy_s>
			68: R_ARM_CALL	memcpy_s
  6c:	e59f3080 	ldr	r3, [pc, #128]	; f4 <hi_mpi_vgs_add_osd_task_array+0xf4>
  70:	e3041a09 	movw	r1, #18953	; 0x4a09
  74:	e34412d8 	movt	r1, #17112	; 0x42d8
  78:	e1a0200d 	mov	r2, sp
  7c:	e08f3003 	add	r3, pc, r3
  80:	e58d52d4 	str	r5, [sp, #724]	; 0x2d4
  84:	e5930000 	ldr	r0, [r3]
  88:	ebfffffe 	bl	0 <ioctl>
			88: R_ARM_CALL	ioctl
  8c:	e59f2064 	ldr	r2, [pc, #100]	; f8 <hi_mpi_vgs_add_osd_task_array+0xf8>
  90:	e59f3058 	ldr	r3, [pc, #88]	; f0 <hi_mpi_vgs_add_osd_task_array+0xf0>
  94:	e08f2002 	add	r2, pc, r2
  98:	e7923003 	ldr	r3, [r2, r3]
  9c:	e5932000 	ldr	r2, [r3]
  a0:	e59d32dc 	ldr	r3, [sp, #732]	; 0x2dc
  a4:	e0332002 	eors	r2, r3, r2
  a8:	1a00000e 	bne	e8 <hi_mpi_vgs_add_osd_task_array+0xe8>
  ac:	e28ddfb9 	add	sp, sp, #740	; 0x2e4
  b0:	e8bd80f0 	pop	{r4, r5, r6, r7, pc}
  b4:	ebfffffe 	bl	0 <hi_mpi_vgs_add_osd_task_array>
			b4: R_ARM_CALL	vgs_check_null_ptr.part.1
  b8:	e3500000 	cmp	r0, #0
  bc:	0affffe1 	beq	48 <hi_mpi_vgs_add_osd_task_array+0x48>
  c0:	e3080006 	movw	r0, #32774	; 0x8006
  c4:	e34a002d 	movt	r0, #41005	; 0xa02d
  c8:	eaffffef 	b	8c <hi_mpi_vgs_add_osd_task_array+0x8c>
  cc:	ebfffffe 	bl	0 <hi_mpi_vgs_add_osd_task_array>
			cc: R_ARM_CALL	vgs_check_null_ptr.part.1
  d0:	e3500000 	cmp	r0, #0
  d4:	1afffff9 	bne	c0 <hi_mpi_vgs_add_osd_task_array+0xc0>
  d8:	eaffffdc 	b	50 <hi_mpi_vgs_add_osd_task_array+0x50>
  dc:	e3080010 	movw	r0, #32784	; 0x8010
  e0:	e34a002d 	movt	r0, #41005	; 0xa02d
  e4:	eaffffe8 	b	8c <hi_mpi_vgs_add_osd_task_array+0x8c>
  e8:	ebfffffe 	bl	0 <__stack_chk_fail>
			e8: R_ARM_CALL	__stack_chk_fail
  ec:	000000cc 	.word	0x000000cc
			ec: R_ARM_GOTPC	_GLOBAL_OFFSET_TABLE_
  f0:	00000000 	.word	0x00000000
			f0: R_ARM_GOT32	__stack_chk_guard
  f4:	00000070 	.word	0x00000070
			f4: R_ARM_REL32	.data.g_device_id
  f8:	0000005c 	.word	0x0000005c
			f8: R_ARM_GOTPC	_GLOBAL_OFFSET_TABLE_

Disassembly of section .text.hi_mpi_vgs_add_rotation_task:

00000000 <hi_mpi_vgs_add_rotation_task>:
   0:	e92d40f0 	push	{r4, r5, r6, r7, lr}
   4:	e1a07002 	mov	r7, r2
   8:	e59f20c0 	ldr	r2, [pc, #192]	; d0 <hi_mpi_vgs_add_rotation_task+0xd0>
   c:	e24ddfb9 	sub	sp, sp, #740	; 0x2e4
  10:	e59f30bc 	ldr	r3, [pc, #188]	; d4 <hi_mpi_vgs_add_rotation_task+0xd4>
  14:	e1a06000 	mov	r6, r0
  18:	e08f2002 	add	r2, pc, r2
  1c:	e1a05001 	mov	r5, r1
  20:	e7923003 	ldr	r3, [r2, r3]
  24:	e5933000 	ldr	r3, [r3]
  28:	e58d32dc 	str	r3, [sp, #732]	; 0x2dc
  2c:	e3a03000 	mov	r3, #0
  30:	ebfffffe 	bl	0 <hi_mpi_vgs_add_rotation_task>
			30: R_ARM_CALL	vgs_check_open
  34:	e3500000 	cmp	r0, #0
  38:	1a000020 	bne	c0 <hi_mpi_vgs_add_rotation_task+0xc0>
  3c:	e3550000 	cmp	r5, #0
  40:	0a000018 	beq	a8 <hi_mpi_vgs_add_rotation_task+0xa8>
  44:	e3a03fb2 	mov	r3, #712	; 0x2c8
  48:	e28d4e2e 	add	r4, sp, #736	; 0x2e0
  4c:	e1a01003 	mov	r1, r3
  50:	e1a02005 	mov	r2, r5
  54:	e52462e0 	str	r6, [r4, #-736]!	; 0xfffffd20
  58:	e28d0008 	add	r0, sp, #8
  5c:	ebfffffe 	bl	0 <memcpy_s>
			5c: R_ARM_CALL	memcpy_s
  60:	e59f3070 	ldr	r3, [pc, #112]	; d8 <hi_mpi_vgs_add_rotation_task+0xd8>
  64:	e3041a0a 	movw	r1, #18954	; 0x4a0a
  68:	e34412d8 	movt	r1, #17112	; 0x42d8
  6c:	e1a02004 	mov	r2, r4
  70:	e08f3003 	add	r3, pc, r3
  74:	e58d72d0 	str	r7, [sp, #720]	; 0x2d0
  78:	e5930000 	ldr	r0, [r3]
  7c:	ebfffffe 	bl	0 <ioctl>
			7c: R_ARM_CALL	ioctl
  80:	e59f2054 	ldr	r2, [pc, #84]	; dc <hi_mpi_vgs_add_rotation_task+0xdc>
  84:	e59f3048 	ldr	r3, [pc, #72]	; d4 <hi_mpi_vgs_add_rotation_task+0xd4>
  88:	e08f2002 	add	r2, pc, r2
  8c:	e7923003 	ldr	r3, [r2, r3]
  90:	e5932000 	ldr	r2, [r3]
  94:	e59d32dc 	ldr	r3, [sp, #732]	; 0x2dc
  98:	e0332002 	eors	r2, r3, r2
  9c:	1a00000a 	bne	cc <hi_mpi_vgs_add_rotation_task+0xcc>
  a0:	e28ddfb9 	add	sp, sp, #740	; 0x2e4
  a4:	e8bd80f0 	pop	{r4, r5, r6, r7, pc}
  a8:	ebfffffe 	bl	0 <hi_mpi_vgs_add_rotation_task>
			a8: R_ARM_CALL	vgs_check_null_ptr.part.1
  ac:	e3500000 	cmp	r0, #0
  b0:	0affffe3 	beq	44 <hi_mpi_vgs_add_rotation_task+0x44>
  b4:	e3080006 	movw	r0, #32774	; 0x8006
  b8:	e34a002d 	movt	r0, #41005	; 0xa02d
  bc:	eaffffef 	b	80 <hi_mpi_vgs_add_rotation_task+0x80>
  c0:	e3080010 	movw	r0, #32784	; 0x8010
  c4:	e34a002d 	movt	r0, #41005	; 0xa02d
  c8:	eaffffec 	b	80 <hi_mpi_vgs_add_rotation_task+0x80>
  cc:	ebfffffe 	bl	0 <__stack_chk_fail>
			cc: R_ARM_CALL	__stack_chk_fail
  d0:	000000b0 	.word	0x000000b0
			d0: R_ARM_GOTPC	_GLOBAL_OFFSET_TABLE_
  d4:	00000000 	.word	0x00000000
			d4: R_ARM_GOT32	__stack_chk_guard
  d8:	00000060 	.word	0x00000060
			d8: R_ARM_REL32	.data.g_device_id
  dc:	0000004c 	.word	0x0000004c
			dc: R_ARM_GOTPC	_GLOBAL_OFFSET_TABLE_

Disassembly of section .text.hi_mpi_vgs_add_luma_task_array:

00000000 <hi_mpi_vgs_add_luma_task_array>:
   0:	e92d43f0 	push	{r4, r5, r6, r7, r8, r9, lr}
   4:	e1a06002 	mov	r6, r2
   8:	e59f2100 	ldr	r2, [pc, #256]	; 110 <hi_mpi_vgs_add_luma_task_array+0x110>
   c:	e1a09003 	mov	r9, r3
  10:	e59f30fc 	ldr	r3, [pc, #252]	; 114 <hi_mpi_vgs_add_luma_task_array+0x114>
  14:	e24ddfb9 	sub	sp, sp, #740	; 0x2e4
  18:	e08f2002 	add	r2, pc, r2
  1c:	e1a08000 	mov	r8, r0
  20:	e59d7300 	ldr	r7, [sp, #768]	; 0x300
  24:	e1a05001 	mov	r5, r1
  28:	e7923003 	ldr	r3, [r2, r3]
  2c:	e5933000 	ldr	r3, [r3]
  30:	e58d32dc 	str	r3, [sp, #732]	; 0x2dc
  34:	e3a03000 	mov	r3, #0
  38:	ebfffffe 	bl	0 <hi_mpi_vgs_add_luma_task_array>
			38: R_ARM_CALL	vgs_check_open
  3c:	e3500000 	cmp	r0, #0
  40:	1a00002e 	bne	100 <hi_mpi_vgs_add_luma_task_array+0x100>
  44:	e3550000 	cmp	r5, #0
  48:	0a00001e 	beq	c8 <hi_mpi_vgs_add_luma_task_array+0xc8>
  4c:	e3560000 	cmp	r6, #0
  50:	0a000022 	beq	e0 <hi_mpi_vgs_add_luma_task_array+0xe0>
  54:	e3570000 	cmp	r7, #0
  58:	0a000024 	beq	f0 <hi_mpi_vgs_add_luma_task_array+0xf0>
  5c:	e3a03fb2 	mov	r3, #712	; 0x2c8
  60:	e28d4e2e 	add	r4, sp, #736	; 0x2e0
  64:	e1a01003 	mov	r1, r3
  68:	e1a02005 	mov	r2, r5
  6c:	e52482e0 	str	r8, [r4, #-736]!	; 0xfffffd20
  70:	e28d0008 	add	r0, sp, #8
  74:	ebfffffe 	bl	0 <memcpy_s>
			74: R_ARM_CALL	memcpy_s
  78:	e59f3098 	ldr	r3, [pc, #152]	; 118 <hi_mpi_vgs_add_luma_task_array+0x118>
  7c:	e3041a0b 	movw	r1, #18955	; 0x4a0b
  80:	e34c12d8 	movt	r1, #49880	; 0xc2d8
  84:	e1a02004 	mov	r2, r4
  88:	e08f3003 	add	r3, pc, r3
  8c:	e58d9004 	str	r9, [sp, #4]
  90:	e5930000 	ldr	r0, [r3]
  94:	e58d62d0 	str	r6, [sp, #720]	; 0x2d0
  98:	e58d72d4 	str	r7, [sp, #724]	; 0x2d4
  9c:	ebfffffe 	bl	0 <ioctl>
			9c: R_ARM_CALL	ioctl
  a0:	e59f2074 	ldr	r2, [pc, #116]	; 11c <hi_mpi_vgs_add_luma_task_array+0x11c>
  a4:	e59f3068 	ldr	r3, [pc, #104]	; 114 <hi_mpi_vgs_add_luma_task_array+0x114>
  a8:	e08f2002 	add	r2, pc, r2
  ac:	e7923003 	ldr	r3, [r2, r3]
  b0:	e5932000 	ldr	r2, [r3]
  b4:	e59d32dc 	ldr	r3, [sp, #732]	; 0x2dc
  b8:	e0332002 	eors	r2, r3, r2
  bc:	1a000012 	bne	10c <hi_mpi_vgs_add_luma_task_array+0x10c>
  c0:	e28ddfb9 	add	sp, sp, #740	; 0x2e4
  c4:	e8bd83f0 	pop	{r4, r5, r6, r7, r8, r9, pc}
  c8:	ebfffffe 	bl	0 <hi_mpi_vgs_add_luma_task_array>
			c8: R_ARM_CALL	vgs_check_null_ptr.part.1
  cc:	e3500000 	cmp	r0, #0
  d0:	0affffdd 	beq	4c <hi_mpi_vgs_add_luma_task_array+0x4c>
  d4:	e3080006 	movw	r0, #32774	; 0x8006
  d8:	e34a002d 	movt	r0, #41005	; 0xa02d
  dc:	eaffffef 	b	a0 <hi_mpi_vgs_add_luma_task_array+0xa0>
  e0:	ebfffffe 	bl	0 <hi_mpi_vgs_add_luma_task_array>
			e0: R_ARM_CALL	vgs_check_null_ptr.part.1
  e4:	e3500000 	cmp	r0, #0
  e8:	1afffff9 	bne	d4 <hi_mpi_vgs_add_luma_task_array+0xd4>
  ec:	eaffffd8 	b	54 <hi_mpi_vgs_add_luma_task_array+0x54>
  f0:	ebfffffe 	bl	0 <hi_mpi_vgs_add_luma_task_array>
			f0: R_ARM_CALL	vgs_check_null_ptr.part.1
  f4:	e3500000 	cmp	r0, #0
  f8:	1afffff5 	bne	d4 <hi_mpi_vgs_add_luma_task_array+0xd4>
  fc:	eaffffd6 	b	5c <hi_mpi_vgs_add_luma_task_array+0x5c>
 100:	e3080010 	movw	r0, #32784	; 0x8010
 104:	e34a002d 	movt	r0, #41005	; 0xa02d
 108:	eaffffe4 	b	a0 <hi_mpi_vgs_add_luma_task_array+0xa0>
 10c:	ebfffffe 	bl	0 <__stack_chk_fail>
			10c: R_ARM_CALL	__stack_chk_fail
 110:	000000f0 	.word	0x000000f0
			110: R_ARM_GOTPC	_GLOBAL_OFFSET_TABLE_
 114:	00000000 	.word	0x00000000
			114: R_ARM_GOT32	__stack_chk_guard
 118:	00000088 	.word	0x00000088
			118: R_ARM_REL32	.data.g_device_id
 11c:	0000006c 	.word	0x0000006c
			11c: R_ARM_GOTPC	_GLOBAL_OFFSET_TABLE_

Disassembly of section .text.HI_MPI_VGS_BeginJob:

00000000 <HI_MPI_VGS_BeginJob>:
   0:	e92d4010 	push	{r4, lr}
   4:	e1a04000 	mov	r4, r0
   8:	ebfffffe 	bl	0 <HI_MPI_VGS_BeginJob>
			8: R_ARM_CALL	vgs_check_open
   c:	e3500000 	cmp	r0, #0
  10:	1a00000f 	bne	54 <HI_MPI_VGS_BeginJob+0x54>
  14:	e3540000 	cmp	r4, #0
  18:	0a000007 	beq	3c <HI_MPI_VGS_BeginJob+0x3c>
  1c:	e59f303c 	ldr	r3, [pc, #60]	; 60 <HI_MPI_VGS_BeginJob+0x60>
  20:	e3a01c4a 	mov	r1, #18944	; 0x4a00
  24:	e34c1004 	movt	r1, #49156	; 0xc004
  28:	e1a02004 	mov	r2, r4
  2c:	e08f3003 	add	r3, pc, r3
  30:	e8bd4010 	pop	{r4, lr}
  34:	e5930000 	ldr	r0, [r3]
  38:	eafffffe 	b	0 <ioctl>
			38: R_ARM_JUMP24	ioctl
  3c:	ebfffffe 	bl	0 <HI_MPI_VGS_BeginJob>
			3c: R_ARM_CALL	vgs_check_null_ptr.part.1
  40:	e3500000 	cmp	r0, #0
  44:	0afffff4 	beq	1c <HI_MPI_VGS_BeginJob+0x1c>
  48:	e3080006 	movw	r0, #32774	; 0x8006
  4c:	e34a002d 	movt	r0, #41005	; 0xa02d
  50:	e8bd8010 	pop	{r4, pc}
  54:	e3080010 	movw	r0, #32784	; 0x8010
  58:	e34a002d 	movt	r0, #41005	; 0xa02d
  5c:	e8bd8010 	pop	{r4, pc}
  60:	0000002c 	.word	0x0000002c
			60: R_ARM_REL32	.data.g_device_id

Disassembly of section .text.HI_MPI_VGS_EndJob:

00000000 <HI_MPI_VGS_EndJob>:
   0:	e59f2080 	ldr	r2, [pc, #128]	; 88 <HI_MPI_VGS_EndJob+0x88>
   4:	e59f3080 	ldr	r3, [pc, #128]	; 8c <HI_MPI_VGS_EndJob+0x8c>
   8:	e08f2002 	add	r2, pc, r2
   c:	e52de004 	push	{lr}		; (str lr, [sp, #-4]!)
  10:	e24dd00c 	sub	sp, sp, #12
  14:	e7923003 	ldr	r3, [r2, r3]
  18:	e5933000 	ldr	r3, [r3]
  1c:	e58d3004 	str	r3, [sp, #4]
  20:	e3a03000 	mov	r3, #0
  24:	e58d0000 	str	r0, [sp]
  28:	ebfffffe 	bl	0 <HI_MPI_VGS_EndJob>
			28: R_ARM_CALL	vgs_check_open
  2c:	e3500000 	cmp	r0, #0
  30:	1a000010 	bne	78 <HI_MPI_VGS_EndJob+0x78>
  34:	e59f3054 	ldr	r3, [pc, #84]	; 90 <HI_MPI_VGS_EndJob+0x90>
  38:	e3041a02 	movw	r1, #18946	; 0x4a02
  3c:	e3441004 	movt	r1, #16388	; 0x4004
  40:	e1a0200d 	mov	r2, sp
  44:	e08f3003 	add	r3, pc, r3
  48:	e5930000 	ldr	r0, [r3]
  4c:	ebfffffe 	bl	0 <ioctl>
			4c: R_ARM_CALL	ioctl
  50:	e59f203c 	ldr	r2, [pc, #60]	; 94 <HI_MPI_VGS_EndJob+0x94>
  54:	e59f3030 	ldr	r3, [pc, #48]	; 8c <HI_MPI_VGS_EndJob+0x8c>
  58:	e08f2002 	add	r2, pc, r2
  5c:	e7923003 	ldr	r3, [r2, r3]
  60:	e5932000 	ldr	r2, [r3]
  64:	e59d3004 	ldr	r3, [sp, #4]
  68:	e0332002 	eors	r2, r3, r2
  6c:	1a000004 	bne	84 <HI_MPI_VGS_EndJob+0x84>
  70:	e28dd00c 	add	sp, sp, #12
  74:	e49df004 	pop	{pc}		; (ldr pc, [sp], #4)
  78:	e3080010 	movw	r0, #32784	; 0x8010
  7c:	e34a002d 	movt	r0, #41005	; 0xa02d
  80:	eafffff2 	b	50 <HI_MPI_VGS_EndJob+0x50>
  84:	ebfffffe 	bl	0 <__stack_chk_fail>
			84: R_ARM_CALL	__stack_chk_fail
  88:	00000078 	.word	0x00000078
			88: R_ARM_GOTPC	_GLOBAL_OFFSET_TABLE_
  8c:	00000000 	.word	0x00000000
			8c: R_ARM_GOT32	__stack_chk_guard
  90:	00000044 	.word	0x00000044
			90: R_ARM_REL32	.data.g_device_id
  94:	00000034 	.word	0x00000034
			94: R_ARM_GOTPC	_GLOBAL_OFFSET_TABLE_

Disassembly of section .text.HI_MPI_VGS_CancelJob:

00000000 <HI_MPI_VGS_CancelJob>:
   0:	e59f2080 	ldr	r2, [pc, #128]	; 88 <HI_MPI_VGS_CancelJob+0x88>
   4:	e59f3080 	ldr	r3, [pc, #128]	; 8c <HI_MPI_VGS_CancelJob+0x8c>
   8:	e08f2002 	add	r2, pc, r2
   c:	e52de004 	push	{lr}		; (str lr, [sp, #-4]!)
  10:	e24dd00c 	sub	sp, sp, #12
  14:	e7923003 	ldr	r3, [r2, r3]
  18:	e5933000 	ldr	r3, [r3]
  1c:	e58d3004 	str	r3, [sp, #4]
  20:	e3a03000 	mov	r3, #0
  24:	e58d0000 	str	r0, [sp]
  28:	ebfffffe 	bl	0 <HI_MPI_VGS_CancelJob>
			28: R_ARM_CALL	vgs_check_open
  2c:	e3500000 	cmp	r0, #0
  30:	1a000010 	bne	78 <HI_MPI_VGS_CancelJob+0x78>
  34:	e59f3054 	ldr	r3, [pc, #84]	; 90 <HI_MPI_VGS_CancelJob+0x90>
  38:	e3041a01 	movw	r1, #18945	; 0x4a01
  3c:	e3441004 	movt	r1, #16388	; 0x4004
  40:	e1a0200d 	mov	r2, sp
  44:	e08f3003 	add	r3, pc, r3
  48:	e5930000 	ldr	r0, [r3]
  4c:	ebfffffe 	bl	0 <ioctl>
			4c: R_ARM_CALL	ioctl
  50:	e59f203c 	ldr	r2, [pc, #60]	; 94 <HI_MPI_VGS_CancelJob+0x94>
  54:	e59f3030 	ldr	r3, [pc, #48]	; 8c <HI_MPI_VGS_CancelJob+0x8c>
  58:	e08f2002 	add	r2, pc, r2
  5c:	e7923003 	ldr	r3, [r2, r3]
  60:	e5932000 	ldr	r2, [r3]
  64:	e59d3004 	ldr	r3, [sp, #4]
  68:	e0332002 	eors	r2, r3, r2
  6c:	1a000004 	bne	84 <HI_MPI_VGS_CancelJob+0x84>
  70:	e28dd00c 	add	sp, sp, #12
  74:	e49df004 	pop	{pc}		; (ldr pc, [sp], #4)
  78:	e3080010 	movw	r0, #32784	; 0x8010
  7c:	e34a002d 	movt	r0, #41005	; 0xa02d
  80:	eafffff2 	b	50 <HI_MPI_VGS_CancelJob+0x50>
  84:	ebfffffe 	bl	0 <__stack_chk_fail>
			84: R_ARM_CALL	__stack_chk_fail
  88:	00000078 	.word	0x00000078
			88: R_ARM_GOTPC	_GLOBAL_OFFSET_TABLE_
  8c:	00000000 	.word	0x00000000
			8c: R_ARM_GOT32	__stack_chk_guard
  90:	00000044 	.word	0x00000044
			90: R_ARM_REL32	.data.g_device_id
  94:	00000034 	.word	0x00000034
			94: R_ARM_GOTPC	_GLOBAL_OFFSET_TABLE_

Disassembly of section .text.HI_MPI_VGS_AddScaleTask:

00000000 <HI_MPI_VGS_AddScaleTask>:
   0:	eafffffe 	b	0 <HI_MPI_VGS_AddScaleTask>
			0: R_ARM_JUMP24	hi_mpi_vgs_add_scale_task

Disassembly of section .text.HI_MPI_VGS_AddDrawLineTask:

00000000 <HI_MPI_VGS_AddDrawLineTask>:
   0:	eafffffe 	b	0 <HI_MPI_VGS_AddDrawLineTask>
			0: R_ARM_JUMP24	hi_mpi_vgs_add_draw_line_task

Disassembly of section .text.HI_MPI_VGS_AddCoverTask:

00000000 <HI_MPI_VGS_AddCoverTask>:
   0:	eafffffe 	b	0 <HI_MPI_VGS_AddCoverTask>
			0: R_ARM_JUMP24	hi_mpi_vgs_add_cover_task

Disassembly of section .text.HI_MPI_VGS_AddOsdTask:

00000000 <HI_MPI_VGS_AddOsdTask>:
   0:	eafffffe 	b	0 <HI_MPI_VGS_AddOsdTask>
			0: R_ARM_JUMP24	hi_mpi_vgs_add_osd_task

Disassembly of section .text.HI_MPI_VGS_AddDrawLineTaskArray:

00000000 <HI_MPI_VGS_AddDrawLineTaskArray>:
   0:	eafffffe 	b	0 <HI_MPI_VGS_AddDrawLineTaskArray>
			0: R_ARM_JUMP24	hi_mpi_vgs_add_draw_line_task_array

Disassembly of section .text.HI_MPI_VGS_AddCoverTaskArray:

00000000 <HI_MPI_VGS_AddCoverTaskArray>:
   0:	eafffffe 	b	0 <HI_MPI_VGS_AddCoverTaskArray>
			0: R_ARM_JUMP24	hi_mpi_vgs_add_cover_task_array

Disassembly of section .text.HI_MPI_VGS_AddOsdTaskArray:

00000000 <HI_MPI_VGS_AddOsdTaskArray>:
   0:	eafffffe 	b	0 <HI_MPI_VGS_AddOsdTaskArray>
			0: R_ARM_JUMP24	hi_mpi_vgs_add_osd_task_array

Disassembly of section .text.HI_MPI_VGS_AddRotationTask:

00000000 <HI_MPI_VGS_AddRotationTask>:
   0:	eafffffe 	b	0 <HI_MPI_VGS_AddRotationTask>
			0: R_ARM_JUMP24	hi_mpi_vgs_add_rotation_task

Disassembly of section .text.HI_MPI_VGS_AddLumaTaskArray:

00000000 <HI_MPI_VGS_AddLumaTaskArray>:
   0:	eafffffe 	b	0 <HI_MPI_VGS_AddLumaTaskArray>
			0: R_ARM_JUMP24	hi_mpi_vgs_add_luma_task_array
