
mpi_mcf.o:     file format elf32-littlearm

SYMBOL TABLE:
00000000 l    df *ABS*	00000000 mpi_mcf.c
00000000 l    d  .text	00000000 .text
00000000 l    d  .data	00000000 .data
00000000 l    d  .bss	00000000 .bss
00000000 l    d  .text.mpi_mcf_check_grp_id.part.0	00000000 .text.mpi_mcf_check_grp_id.part.0
00000000 l     F .text.mpi_mcf_check_grp_id.part.0	0000005c mpi_mcf_check_grp_id.part.0
00000000 l       .rodata.mpi_mcf_check_grp_id.part.0.str1.4	00000000 .LC0
00000000 l    d  .text.mpi_mcf_check_null_ptr.part.1	00000000 .text.mpi_mcf_check_null_ptr.part.1
00000000 l     F .text.mpi_mcf_check_null_ptr.part.1	0000004c mpi_mcf_check_null_ptr.part.1
00000000 l       .rodata.mpi_mcf_check_null_ptr.part.1.str1.4	00000000 .LC1
00000000 l    d  .text.mpi_mcf_check_grp_open	00000000 .text.mpi_mcf_check_grp_open
00000000 l     F .text.mpi_mcf_check_grp_open	00000168 mpi_mcf_check_grp_open
00000000 l       .rodata.mpi_mcf_check_grp_open.str1.4	00000000 .LC2
0000000c l       .rodata.mpi_mcf_check_grp_open.str1.4	00000000 .LC3
00000000 l    d  .text.mpi_mcf_check_chn_open	00000000 .text.mpi_mcf_check_chn_open
00000000 l     F .text.mpi_mcf_check_chn_open	00000178 mpi_mcf_check_chn_open
00000000 l       .rodata.mpi_mcf_check_chn_open.str1.4	00000000 .LC4
00000000 l    d  .text.hi_mpi_mcf_create_grp	00000000 .text.hi_mpi_mcf_create_grp
00000000 l    d  .text.hi_mpi_mcf_destroy_grp	00000000 .text.hi_mpi_mcf_destroy_grp
00000000 l    d  .text.hi_mpi_mcf_start_grp	00000000 .text.hi_mpi_mcf_start_grp
00000000 l    d  .text.hi_mpi_mcf_stop_grp	00000000 .text.hi_mpi_mcf_stop_grp
00000000 l    d  .text.hi_mpi_mcf_set_grp_attr	00000000 .text.hi_mpi_mcf_set_grp_attr
00000000 l    d  .text.hi_mpi_mcf_get_grp_attr	00000000 .text.hi_mpi_mcf_get_grp_attr
00000000 l    d  .text.hi_mpi_mcf_set_alg_param	00000000 .text.hi_mpi_mcf_set_alg_param
00000000 l    d  .text.hi_mpi_mcf_get_alg_param	00000000 .text.hi_mpi_mcf_get_alg_param
00000000 l    d  .text.hi_mpi_mcf_enable_chn	00000000 .text.hi_mpi_mcf_enable_chn
00000000 l       .rodata.hi_mpi_mcf_enable_chn.str1.4	00000000 .LC5
00000000 l    d  .text.hi_mpi_mcf_disable_chn	00000000 .text.hi_mpi_mcf_disable_chn
00000000 l    d  .text.hi_mpi_mcf_close_fd	00000000 .text.hi_mpi_mcf_close_fd
00000000 l       .rodata.hi_mpi_mcf_close_fd.str1.4	00000000 .LC6
00000018 l       .rodata.hi_mpi_mcf_close_fd.str1.4	00000000 .LC7
00000000 l    d  .bss.g_mcf_mutex	00000000 .bss.g_mcf_mutex
00000000 l     O .bss.g_mcf_mutex	00000018 g_mcf_mutex
00000000 l    d  .data.g_mcf_chn_fd	00000000 .data.g_mcf_chn_fd
00000000 l     O .data.g_mcf_chn_fd	00000004 g_mcf_chn_fd
00000000 l    d  .data.g_mcf_grp_fd	00000000 .data.g_mcf_grp_fd
00000000 l     O .data.g_mcf_grp_fd	00000004 g_mcf_grp_fd
00000000 l    d  .rodata.__FUNCTION__.10211	00000000 .rodata.__FUNCTION__.10211
00000000 l     O .rodata.__FUNCTION__.10211	00000017 __FUNCTION__.10211
00000000 l    d  .rodata.__FUNCTION__.10217	00000000 .rodata.__FUNCTION__.10217
00000000 l     O .rodata.__FUNCTION__.10217	00000017 __FUNCTION__.10217
00000000 l    d  .rodata.__FUNCTION__.10221	00000000 .rodata.__FUNCTION__.10221
00000000 l     O .rodata.__FUNCTION__.10221	00000017 __FUNCTION__.10221
00000000 l    d  .rodata.__FUNCTION__.10225	00000000 .rodata.__FUNCTION__.10225
00000000 l     O .rodata.__FUNCTION__.10225	00000015 __FUNCTION__.10225
00000000 l    d  .rodata.__FUNCTION__.10229	00000000 .rodata.__FUNCTION__.10229
00000000 l     O .rodata.__FUNCTION__.10229	00000015 __FUNCTION__.10229
00000000 l    d  .rodata.hi_mpi_mcf_close_fd.str1.4	00000000 .rodata.hi_mpi_mcf_close_fd.str1.4
00000000 l    d  .rodata.hi_mpi_mcf_enable_chn.str1.4	00000000 .rodata.hi_mpi_mcf_enable_chn.str1.4
00000000 l    d  .rodata.mpi_mcf_check_chn_open.str1.4	00000000 .rodata.mpi_mcf_check_chn_open.str1.4
00000000 l    d  .rodata.mpi_mcf_check_grp_id.part.0.str1.4	00000000 .rodata.mpi_mcf_check_grp_id.part.0.str1.4
00000000 l    d  .rodata.mpi_mcf_check_grp_open.str1.4	00000000 .rodata.mpi_mcf_check_grp_open.str1.4
00000000 l    d  .rodata.mpi_mcf_check_null_ptr.part.1.str1.4	00000000 .rodata.mpi_mcf_check_null_ptr.part.1.str1.4
00000000 l    d  .note.GNU-stack	00000000 .note.GNU-stack
00000000 l    d  .comment	00000000 .comment
00000000 l    d  .ARM.attributes	00000000 .ARM.attributes
00000000         *UND*	00000000 fprintf
00000000         *UND*	00000000 _GLOBAL_OFFSET_TABLE_
00000000         *UND*	00000000 stderr
00000000         *UND*	00000000 pthread_mutex_lock
00000000         *UND*	00000000 pthread_mutex_unlock
00000000         *UND*	00000000 open
00000000         *UND*	00000000 ioctl
00000000         *UND*	00000000 close
00000000         *UND*	00000000 __stack_chk_fail
00000000         *UND*	00000000 __stack_chk_guard
00000000 g     F .text.hi_mpi_mcf_create_grp	0000006c hi_mpi_mcf_create_grp
00000000 g     F .text.hi_mpi_mcf_destroy_grp	00000048 hi_mpi_mcf_destroy_grp
00000000 g     F .text.hi_mpi_mcf_start_grp	00000048 hi_mpi_mcf_start_grp
00000000 g     F .text.hi_mpi_mcf_stop_grp	00000048 hi_mpi_mcf_stop_grp
00000000 g     F .text.hi_mpi_mcf_set_grp_attr	0000006c hi_mpi_mcf_set_grp_attr
00000000 g     F .text.hi_mpi_mcf_get_grp_attr	0000006c hi_mpi_mcf_get_grp_attr
00000000 g     F .text.hi_mpi_mcf_set_alg_param	0000006c hi_mpi_mcf_set_alg_param
00000000 g     F .text.hi_mpi_mcf_get_alg_param	0000006c hi_mpi_mcf_get_alg_param
00000000 g     F .text.hi_mpi_mcf_enable_chn	000000bc hi_mpi_mcf_enable_chn
00000000 g     F .text.hi_mpi_mcf_disable_chn	000000bc hi_mpi_mcf_disable_chn
00000000 g     F .text.hi_mpi_mcf_close_fd	00000134 hi_mpi_mcf_close_fd
00000000         *UND*	00000000 perror



Disassembly of section .text.mpi_mcf_check_grp_id.part.0:

00000000 <mpi_mcf_check_grp_id.part.0>:
   0:	e59f1044 	ldr	r1, [pc, #68]	; 4c <mpi_mcf_check_grp_id.part.0+0x4c>
   4:	e3a0307c 	mov	r3, #124	; 0x7c
   8:	e59fc040 	ldr	ip, [pc, #64]	; 50 <mpi_mcf_check_grp_id.part.0+0x50>
   c:	e08f1001 	add	r1, pc, r1
  10:	e52de004 	push	{lr}		; (str lr, [sp, #-4]!)
  14:	e24dd00c 	sub	sp, sp, #12
  18:	e791c00c 	ldr	ip, [r1, ip]
  1c:	e59f2030 	ldr	r2, [pc, #48]	; 54 <mpi_mcf_check_grp_id.part.0+0x54>
  20:	e59cc000 	ldr	ip, [ip]
  24:	e59f102c 	ldr	r1, [pc, #44]	; 58 <mpi_mcf_check_grp_id.part.0+0x58>
  28:	e58d0000 	str	r0, [sp]
  2c:	e1a0000c 	mov	r0, ip
  30:	e08f2002 	add	r2, pc, r2
  34:	e08f1001 	add	r1, pc, r1
  38:	ebfffffe 	bl	0 <fprintf>
			38: R_ARM_CALL	fprintf
  3c:	e3080001 	movw	r0, #32769	; 0x8001
  40:	e34a003d 	movt	r0, #41021	; 0xa03d
  44:	e28dd00c 	add	sp, sp, #12
  48:	e49df004 	pop	{pc}		; (ldr pc, [sp], #4)
  4c:	00000038 	.word	0x00000038
			4c: R_ARM_GOTPC	_GLOBAL_OFFSET_TABLE_
  50:	00000000 	.word	0x00000000
			50: R_ARM_GOT32	stderr
  54:	0000001c 	.word	0x0000001c
			54: R_ARM_REL32	.rodata.__FUNCTION__.10225
  58:	0000001c 	.word	0x0000001c
			58: R_ARM_REL32	.LC0

Disassembly of section .text.mpi_mcf_check_null_ptr.part.1:

00000000 <mpi_mcf_check_null_ptr.part.1>:
   0:	e59f1034 	ldr	r1, [pc, #52]	; 3c <mpi_mcf_check_null_ptr.part.1+0x3c>
   4:	e3a03072 	mov	r3, #114	; 0x72
   8:	e59f0030 	ldr	r0, [pc, #48]	; 40 <mpi_mcf_check_null_ptr.part.1+0x40>
   c:	e08f1001 	add	r1, pc, r1
  10:	e92d4010 	push	{r4, lr}
  14:	e59f2028 	ldr	r2, [pc, #40]	; 44 <mpi_mcf_check_null_ptr.part.1+0x44>
  18:	e7910000 	ldr	r0, [r1, r0]
  1c:	e59f1024 	ldr	r1, [pc, #36]	; 48 <mpi_mcf_check_null_ptr.part.1+0x48>
  20:	e08f2002 	add	r2, pc, r2
  24:	e08f1001 	add	r1, pc, r1
  28:	e5900000 	ldr	r0, [r0]
  2c:	ebfffffe 	bl	0 <fprintf>
			2c: R_ARM_CALL	fprintf
  30:	e3080006 	movw	r0, #32774	; 0x8006
  34:	e34a003d 	movt	r0, #41021	; 0xa03d
  38:	e8bd8010 	pop	{r4, pc}
  3c:	00000028 	.word	0x00000028
			3c: R_ARM_GOTPC	_GLOBAL_OFFSET_TABLE_
  40:	00000000 	.word	0x00000000
			40: R_ARM_GOT32	stderr
  44:	0000001c 	.word	0x0000001c
			44: R_ARM_REL32	.rodata.__FUNCTION__.10221
  48:	0000001c 	.word	0x0000001c
			48: R_ARM_REL32	.LC1

Disassembly of section .text.mpi_mcf_check_grp_open:

00000000 <mpi_mcf_check_grp_open>:
   0:	e59f2134 	ldr	r2, [pc, #308]	; 13c <mpi_mcf_check_grp_open+0x13c>
   4:	e92d41f0 	push	{r4, r5, r6, r7, r8, lr}
   8:	e1a04000 	mov	r4, r0
   c:	e08f2002 	add	r2, pc, r2
  10:	e24dd010 	sub	sp, sp, #16
  14:	e59f6124 	ldr	r6, [pc, #292]	; 140 <mpi_mcf_check_grp_open+0x140>
  18:	e59f5124 	ldr	r5, [pc, #292]	; 144 <mpi_mcf_check_grp_open+0x144>
  1c:	e59f3124 	ldr	r3, [pc, #292]	; 148 <mpi_mcf_check_grp_open+0x148>
  20:	e08f6006 	add	r6, pc, r6
  24:	e7923003 	ldr	r3, [r2, r3]
  28:	e1a00006 	mov	r0, r6
  2c:	e08f5005 	add	r5, pc, r5
  30:	e5933000 	ldr	r3, [r3]
  34:	e58d300c 	str	r3, [sp, #12]
  38:	e3a03000 	mov	r3, #0
  3c:	ebfffffe 	bl	0 <pthread_mutex_lock>
			3c: R_ARM_CALL	pthread_mutex_lock
  40:	e7953104 	ldr	r3, [r5, r4, lsl #2]
  44:	e59f7100 	ldr	r7, [pc, #256]	; 14c <mpi_mcf_check_grp_open+0x14c>
  48:	e3530000 	cmp	r3, #0
  4c:	e08f7007 	add	r7, pc, r7
  50:	ba00000d 	blt	8c <mpi_mcf_check_grp_open+0x8c>
  54:	e59f00f4 	ldr	r0, [pc, #244]	; 150 <mpi_mcf_check_grp_open+0x150>
  58:	e08f0000 	add	r0, pc, r0
  5c:	ebfffffe 	bl	0 <pthread_mutex_unlock>
			5c: R_ARM_CALL	pthread_mutex_unlock
  60:	e3a00000 	mov	r0, #0
  64:	e59f20e8 	ldr	r2, [pc, #232]	; 154 <mpi_mcf_check_grp_open+0x154>
  68:	e59f30d8 	ldr	r3, [pc, #216]	; 148 <mpi_mcf_check_grp_open+0x148>
  6c:	e08f2002 	add	r2, pc, r2
  70:	e7923003 	ldr	r3, [r2, r3]
  74:	e5932000 	ldr	r2, [r3]
  78:	e59d300c 	ldr	r3, [sp, #12]
  7c:	e0332002 	eors	r2, r3, r2
  80:	1a00002c 	bne	138 <mpi_mcf_check_grp_open+0x138>
  84:	e28dd010 	add	sp, sp, #16
  88:	e8bd81f0 	pop	{r4, r5, r6, r7, r8, pc}
  8c:	e59f00c4 	ldr	r0, [pc, #196]	; 158 <mpi_mcf_check_grp_open+0x158>
  90:	e3a01000 	mov	r1, #0
  94:	e08f0000 	add	r0, pc, r0
  98:	ebfffffe 	bl	0 <open>
			98: R_ARM_CALL	open
  9c:	e7850104 	str	r0, [r5, r4, lsl #2]
  a0:	e3500000 	cmp	r0, #0
  a4:	e1a08000 	mov	r8, r0
  a8:	ba000011 	blt	f4 <mpi_mcf_check_grp_open+0xf4>
  ac:	e28d2010 	add	r2, sp, #16
  b0:	e3a01b03 	mov	r1, #3072	; 0xc00
  b4:	e1a03804 	lsl	r3, r4, #16
  b8:	e3441004 	movt	r1, #16388	; 0x4004
  bc:	e20338ff 	and	r3, r3, #16711680	; 0xff0000
  c0:	e5223008 	str	r3, [r2, #-8]!
  c4:	ebfffffe 	bl	0 <ioctl>
			c4: R_ARM_CALL	ioctl
  c8:	e3500000 	cmp	r0, #0
  cc:	0affffe0 	beq	54 <mpi_mcf_check_grp_open+0x54>
  d0:	e1a00008 	mov	r0, r8
  d4:	ebfffffe 	bl	0 <close>
			d4: R_ARM_CALL	close
  d8:	e3e03000 	mvn	r3, #0
  dc:	e1a00006 	mov	r0, r6
  e0:	e7853104 	str	r3, [r5, r4, lsl #2]
  e4:	ebfffffe 	bl	0 <pthread_mutex_unlock>
			e4: R_ARM_CALL	pthread_mutex_unlock
  e8:	e3080010 	movw	r0, #32784	; 0x8010
  ec:	e34a003d 	movt	r0, #41021	; 0xa03d
  f0:	eaffffdb 	b	64 <mpi_mcf_check_grp_open+0x64>
  f4:	e1a00006 	mov	r0, r6
  f8:	ebfffffe 	bl	0 <pthread_mutex_unlock>
			f8: R_ARM_CALL	pthread_mutex_unlock
  fc:	e59f2058 	ldr	r2, [pc, #88]	; 15c <mpi_mcf_check_grp_open+0x15c>
 100:	e3a03041 	mov	r3, #65	; 0x41
 104:	e7951104 	ldr	r1, [r5, r4, lsl #2]
 108:	e7970002 	ldr	r0, [r7, r2]
 10c:	e59f204c 	ldr	r2, [pc, #76]	; 160 <mpi_mcf_check_grp_open+0x160>
 110:	e5900000 	ldr	r0, [r0]
 114:	e58d1004 	str	r1, [sp, #4]
 118:	e59f1044 	ldr	r1, [pc, #68]	; 164 <mpi_mcf_check_grp_open+0x164>
 11c:	e08f2002 	add	r2, pc, r2
 120:	e58d4000 	str	r4, [sp]
 124:	e08f1001 	add	r1, pc, r1
 128:	ebfffffe 	bl	0 <fprintf>
			128: R_ARM_CALL	fprintf
 12c:	e3080010 	movw	r0, #32784	; 0x8010
 130:	e34a003d 	movt	r0, #41021	; 0xa03d
 134:	eaffffca 	b	64 <mpi_mcf_check_grp_open+0x64>
 138:	ebfffffe 	bl	0 <__stack_chk_fail>
			138: R_ARM_CALL	__stack_chk_fail
 13c:	00000128 	.word	0x00000128
			13c: R_ARM_GOTPC	_GLOBAL_OFFSET_TABLE_
 140:	00000118 	.word	0x00000118
			140: R_ARM_REL32	.bss.g_mcf_mutex
 144:	00000110 	.word	0x00000110
			144: R_ARM_REL32	.data.g_mcf_grp_fd
 148:	00000000 	.word	0x00000000
			148: R_ARM_GOT32	__stack_chk_guard
 14c:	000000f8 	.word	0x000000f8
			14c: R_ARM_GOTPC	_GLOBAL_OFFSET_TABLE_
 150:	000000f0 	.word	0x000000f0
			150: R_ARM_REL32	.bss.g_mcf_mutex
 154:	000000e0 	.word	0x000000e0
			154: R_ARM_GOTPC	_GLOBAL_OFFSET_TABLE_
 158:	000000bc 	.word	0x000000bc
			158: R_ARM_REL32	.LC2
 15c:	00000000 	.word	0x00000000
			15c: R_ARM_GOT32	stderr
 160:	0000003c 	.word	0x0000003c
			160: R_ARM_REL32	.rodata.__FUNCTION__.10211
 164:	00000038 	.word	0x00000038
			164: R_ARM_REL32	.LC3

Disassembly of section .text.mpi_mcf_check_chn_open:

00000000 <mpi_mcf_check_chn_open>:
   0:	e59f2144 	ldr	r2, [pc, #324]	; 14c <mpi_mcf_check_chn_open+0x14c>
   4:	e92d47f0 	push	{r4, r5, r6, r7, r8, r9, sl, lr}
   8:	e24dd018 	sub	sp, sp, #24
   c:	e08f2002 	add	r2, pc, r2
  10:	e1a04000 	mov	r4, r0
  14:	e59f8134 	ldr	r8, [pc, #308]	; 150 <mpi_mcf_check_chn_open+0x150>
  18:	e1a05001 	mov	r5, r1
  1c:	e59f6130 	ldr	r6, [pc, #304]	; 154 <mpi_mcf_check_chn_open+0x154>
  20:	e59f3130 	ldr	r3, [pc, #304]	; 158 <mpi_mcf_check_chn_open+0x158>
  24:	e0807001 	add	r7, r0, r1
  28:	e7923003 	ldr	r3, [r2, r3]
  2c:	e08f8008 	add	r8, pc, r8
  30:	e08f6006 	add	r6, pc, r6
  34:	e1a00008 	mov	r0, r8
  38:	e5933000 	ldr	r3, [r3]
  3c:	e58d3014 	str	r3, [sp, #20]
  40:	e3a03000 	mov	r3, #0
  44:	ebfffffe 	bl	0 <pthread_mutex_lock>
			44: R_ARM_CALL	pthread_mutex_lock
  48:	e7963107 	ldr	r3, [r6, r7, lsl #2]
  4c:	e59fa108 	ldr	sl, [pc, #264]	; 15c <mpi_mcf_check_chn_open+0x15c>
  50:	e3530000 	cmp	r3, #0
  54:	e08fa00a 	add	sl, pc, sl
  58:	ba00000d 	blt	94 <mpi_mcf_check_chn_open+0x94>
  5c:	e59f00fc 	ldr	r0, [pc, #252]	; 160 <mpi_mcf_check_chn_open+0x160>
  60:	e08f0000 	add	r0, pc, r0
  64:	ebfffffe 	bl	0 <pthread_mutex_unlock>
			64: R_ARM_CALL	pthread_mutex_unlock
  68:	e3a00000 	mov	r0, #0
  6c:	e59f20f0 	ldr	r2, [pc, #240]	; 164 <mpi_mcf_check_chn_open+0x164>
  70:	e59f30e0 	ldr	r3, [pc, #224]	; 158 <mpi_mcf_check_chn_open+0x158>
  74:	e08f2002 	add	r2, pc, r2
  78:	e7923003 	ldr	r3, [r2, r3]
  7c:	e5932000 	ldr	r2, [r3]
  80:	e59d3014 	ldr	r3, [sp, #20]
  84:	e0332002 	eors	r2, r3, r2
  88:	1a00002e 	bne	148 <mpi_mcf_check_chn_open+0x148>
  8c:	e28dd018 	add	sp, sp, #24
  90:	e8bd87f0 	pop	{r4, r5, r6, r7, r8, r9, sl, pc}
  94:	e59f00cc 	ldr	r0, [pc, #204]	; 168 <mpi_mcf_check_chn_open+0x168>
  98:	e3a01000 	mov	r1, #0
  9c:	e08f0000 	add	r0, pc, r0
  a0:	ebfffffe 	bl	0 <open>
			a0: R_ARM_CALL	open
  a4:	e7860107 	str	r0, [r6, r7, lsl #2]
  a8:	e3500000 	cmp	r0, #0
  ac:	e1a09000 	mov	r9, r0
  b0:	ba000013 	blt	104 <mpi_mcf_check_chn_open+0x104>
  b4:	e1a04804 	lsl	r4, r4, #16
  b8:	e28d2018 	add	r2, sp, #24
  bc:	e6ef5075 	uxtb	r5, r5
  c0:	e20448ff 	and	r4, r4, #16711680	; 0xff0000
  c4:	e1844005 	orr	r4, r4, r5
  c8:	e3a01b03 	mov	r1, #3072	; 0xc00
  cc:	e5224008 	str	r4, [r2, #-8]!
  d0:	e3441004 	movt	r1, #16388	; 0x4004
  d4:	ebfffffe 	bl	0 <ioctl>
			d4: R_ARM_CALL	ioctl
  d8:	e3500000 	cmp	r0, #0
  dc:	0affffde 	beq	5c <mpi_mcf_check_chn_open+0x5c>
  e0:	e1a00009 	mov	r0, r9
  e4:	ebfffffe 	bl	0 <close>
			e4: R_ARM_CALL	close
  e8:	e3e03000 	mvn	r3, #0
  ec:	e1a00008 	mov	r0, r8
  f0:	e7863107 	str	r3, [r6, r7, lsl #2]
  f4:	ebfffffe 	bl	0 <pthread_mutex_unlock>
			f4: R_ARM_CALL	pthread_mutex_unlock
  f8:	e3080010 	movw	r0, #32784	; 0x8010
  fc:	e34a003d 	movt	r0, #41021	; 0xa03d
 100:	eaffffd9 	b	6c <mpi_mcf_check_chn_open+0x6c>
 104:	e1a00008 	mov	r0, r8
 108:	ebfffffe 	bl	0 <pthread_mutex_unlock>
			108: R_ARM_CALL	pthread_mutex_unlock
 10c:	e59f2058 	ldr	r2, [pc, #88]	; 16c <mpi_mcf_check_chn_open+0x16c>
 110:	e3a0305d 	mov	r3, #93	; 0x5d
 114:	e7961107 	ldr	r1, [r6, r7, lsl #2]
 118:	e79a0002 	ldr	r0, [sl, r2]
 11c:	e59f204c 	ldr	r2, [pc, #76]	; 170 <mpi_mcf_check_chn_open+0x170>
 120:	e5900000 	ldr	r0, [r0]
 124:	e58d1008 	str	r1, [sp, #8]
 128:	e59f1044 	ldr	r1, [pc, #68]	; 174 <mpi_mcf_check_chn_open+0x174>
 12c:	e08f2002 	add	r2, pc, r2
 130:	e88d0030 	stm	sp, {r4, r5}
 134:	e08f1001 	add	r1, pc, r1
 138:	ebfffffe 	bl	0 <fprintf>
			138: R_ARM_CALL	fprintf
 13c:	e3080010 	movw	r0, #32784	; 0x8010
 140:	e34a003d 	movt	r0, #41021	; 0xa03d
 144:	eaffffc8 	b	6c <mpi_mcf_check_chn_open+0x6c>
 148:	ebfffffe 	bl	0 <__stack_chk_fail>
			148: R_ARM_CALL	__stack_chk_fail
 14c:	00000138 	.word	0x00000138
			14c: R_ARM_GOTPC	_GLOBAL_OFFSET_TABLE_
 150:	0000011c 	.word	0x0000011c
			150: R_ARM_REL32	.bss.g_mcf_mutex
 154:	0000011c 	.word	0x0000011c
			154: R_ARM_REL32	.data.g_mcf_chn_fd
 158:	00000000 	.word	0x00000000
			158: R_ARM_GOT32	__stack_chk_guard
 15c:	00000100 	.word	0x00000100
			15c: R_ARM_GOTPC	_GLOBAL_OFFSET_TABLE_
 160:	000000f8 	.word	0x000000f8
			160: R_ARM_REL32	.bss.g_mcf_mutex
 164:	000000e8 	.word	0x000000e8
			164: R_ARM_GOTPC	_GLOBAL_OFFSET_TABLE_
 168:	000000c4 	.word	0x000000c4
			168: R_ARM_REL32	.LC2
 16c:	00000000 	.word	0x00000000
			16c: R_ARM_GOT32	stderr
 170:	0000003c 	.word	0x0000003c
			170: R_ARM_REL32	.rodata.__FUNCTION__.10217
 174:	00000038 	.word	0x00000038
			174: R_ARM_REL32	.LC4

Disassembly of section .text.hi_mpi_mcf_create_grp:

00000000 <hi_mpi_mcf_create_grp>:
   0:	e92d4070 	push	{r4, r5, r6, lr}
   4:	e2505000 	subs	r5, r0, #0
   8:	e1a04001 	mov	r4, r1
   c:	1a00000d 	bne	48 <hi_mpi_mcf_create_grp+0x48>
  10:	e3540000 	cmp	r4, #0
  14:	0a00000f 	beq	58 <hi_mpi_mcf_create_grp+0x58>
  18:	e1a00005 	mov	r0, r5
  1c:	ebfffffe 	bl	0 <hi_mpi_mcf_create_grp>
			1c: R_ARM_CALL	mpi_mcf_check_grp_open
  20:	e3500000 	cmp	r0, #0
  24:	18bd8070 	popne	{r4, r5, r6, pc}
  28:	e59f3038 	ldr	r3, [pc, #56]	; 68 <hi_mpi_mcf_create_grp+0x68>
  2c:	e3001c02 	movw	r1, #3074	; 0xc02
  30:	e3441078 	movt	r1, #16504	; 0x4078
  34:	e1a02004 	mov	r2, r4
  38:	e08f3003 	add	r3, pc, r3
  3c:	e7930105 	ldr	r0, [r3, r5, lsl #2]
  40:	e8bd4070 	pop	{r4, r5, r6, lr}
  44:	eafffffe 	b	0 <ioctl>
			44: R_ARM_JUMP24	ioctl
  48:	ebfffffe 	bl	0 <hi_mpi_mcf_create_grp>
			48: R_ARM_CALL	mpi_mcf_check_grp_id.part.0
  4c:	e3500000 	cmp	r0, #0
  50:	18bd8070 	popne	{r4, r5, r6, pc}
  54:	eaffffed 	b	10 <hi_mpi_mcf_create_grp+0x10>
  58:	ebfffffe 	bl	0 <hi_mpi_mcf_create_grp>
			58: R_ARM_CALL	mpi_mcf_check_null_ptr.part.1
  5c:	e3500000 	cmp	r0, #0
  60:	18bd8070 	popne	{r4, r5, r6, pc}
  64:	eaffffeb 	b	18 <hi_mpi_mcf_create_grp+0x18>
  68:	00000028 	.word	0x00000028
			68: R_ARM_REL32	.data.g_mcf_grp_fd

Disassembly of section .text.hi_mpi_mcf_destroy_grp:

00000000 <hi_mpi_mcf_destroy_grp>:
   0:	e92d4010 	push	{r4, lr}
   4:	e2504000 	subs	r4, r0, #0
   8:	1a000009 	bne	34 <hi_mpi_mcf_destroy_grp+0x34>
   c:	e1a00004 	mov	r0, r4
  10:	ebfffffe 	bl	0 <hi_mpi_mcf_destroy_grp>
			10: R_ARM_CALL	mpi_mcf_check_grp_open
  14:	e3500000 	cmp	r0, #0
  18:	18bd8010 	popne	{r4, pc}
  1c:	e59f3020 	ldr	r3, [pc, #32]	; 44 <hi_mpi_mcf_destroy_grp+0x44>
  20:	e3001c03 	movw	r1, #3075	; 0xc03
  24:	e08f3003 	add	r3, pc, r3
  28:	e7930104 	ldr	r0, [r3, r4, lsl #2]
  2c:	e8bd4010 	pop	{r4, lr}
  30:	eafffffe 	b	0 <ioctl>
			30: R_ARM_JUMP24	ioctl
  34:	ebfffffe 	bl	0 <hi_mpi_mcf_destroy_grp>
			34: R_ARM_CALL	mpi_mcf_check_grp_id.part.0
  38:	e3500000 	cmp	r0, #0
  3c:	18bd8010 	popne	{r4, pc}
  40:	eafffff1 	b	c <hi_mpi_mcf_destroy_grp+0xc>
  44:	00000018 	.word	0x00000018
			44: R_ARM_REL32	.data.g_mcf_grp_fd

Disassembly of section .text.hi_mpi_mcf_start_grp:

00000000 <hi_mpi_mcf_start_grp>:
   0:	e92d4010 	push	{r4, lr}
   4:	e2504000 	subs	r4, r0, #0
   8:	1a000009 	bne	34 <hi_mpi_mcf_start_grp+0x34>
   c:	e1a00004 	mov	r0, r4
  10:	ebfffffe 	bl	0 <hi_mpi_mcf_start_grp>
			10: R_ARM_CALL	mpi_mcf_check_grp_open
  14:	e3500000 	cmp	r0, #0
  18:	18bd8010 	popne	{r4, pc}
  1c:	e59f3020 	ldr	r3, [pc, #32]	; 44 <hi_mpi_mcf_start_grp+0x44>
  20:	e3001c04 	movw	r1, #3076	; 0xc04
  24:	e08f3003 	add	r3, pc, r3
  28:	e7930104 	ldr	r0, [r3, r4, lsl #2]
  2c:	e8bd4010 	pop	{r4, lr}
  30:	eafffffe 	b	0 <ioctl>
			30: R_ARM_JUMP24	ioctl
  34:	ebfffffe 	bl	0 <hi_mpi_mcf_start_grp>
			34: R_ARM_CALL	mpi_mcf_check_grp_id.part.0
  38:	e3500000 	cmp	r0, #0
  3c:	18bd8010 	popne	{r4, pc}
  40:	eafffff1 	b	c <hi_mpi_mcf_start_grp+0xc>
  44:	00000018 	.word	0x00000018
			44: R_ARM_REL32	.data.g_mcf_grp_fd

Disassembly of section .text.hi_mpi_mcf_stop_grp:

00000000 <hi_mpi_mcf_stop_grp>:
   0:	e92d4010 	push	{r4, lr}
   4:	e2504000 	subs	r4, r0, #0
   8:	1a000009 	bne	34 <hi_mpi_mcf_stop_grp+0x34>
   c:	e1a00004 	mov	r0, r4
  10:	ebfffffe 	bl	0 <hi_mpi_mcf_stop_grp>
			10: R_ARM_CALL	mpi_mcf_check_grp_open
  14:	e3500000 	cmp	r0, #0
  18:	18bd8010 	popne	{r4, pc}
  1c:	e59f3020 	ldr	r3, [pc, #32]	; 44 <hi_mpi_mcf_stop_grp+0x44>
  20:	e3001c05 	movw	r1, #3077	; 0xc05
  24:	e08f3003 	add	r3, pc, r3
  28:	e7930104 	ldr	r0, [r3, r4, lsl #2]
  2c:	e8bd4010 	pop	{r4, lr}
  30:	eafffffe 	b	0 <ioctl>
			30: R_ARM_JUMP24	ioctl
  34:	ebfffffe 	bl	0 <hi_mpi_mcf_stop_grp>
			34: R_ARM_CALL	mpi_mcf_check_grp_id.part.0
  38:	e3500000 	cmp	r0, #0
  3c:	18bd8010 	popne	{r4, pc}
  40:	eafffff1 	b	c <hi_mpi_mcf_stop_grp+0xc>
  44:	00000018 	.word	0x00000018
			44: R_ARM_REL32	.data.g_mcf_grp_fd

Disassembly of section .text.hi_mpi_mcf_set_grp_attr:

00000000 <hi_mpi_mcf_set_grp_attr>:
   0:	e92d4070 	push	{r4, r5, r6, lr}
   4:	e2505000 	subs	r5, r0, #0
   8:	e1a04001 	mov	r4, r1
   c:	1a00000d 	bne	48 <hi_mpi_mcf_set_grp_attr+0x48>
  10:	e3540000 	cmp	r4, #0
  14:	0a00000f 	beq	58 <hi_mpi_mcf_set_grp_attr+0x58>
  18:	e1a00005 	mov	r0, r5
  1c:	ebfffffe 	bl	0 <hi_mpi_mcf_set_grp_attr>
			1c: R_ARM_CALL	mpi_mcf_check_grp_open
  20:	e3500000 	cmp	r0, #0
  24:	18bd8070 	popne	{r4, r5, r6, pc}
  28:	e59f3038 	ldr	r3, [pc, #56]	; 68 <hi_mpi_mcf_set_grp_attr+0x68>
  2c:	e3001c07 	movw	r1, #3079	; 0xc07
  30:	e3441078 	movt	r1, #16504	; 0x4078
  34:	e1a02004 	mov	r2, r4
  38:	e08f3003 	add	r3, pc, r3
  3c:	e7930105 	ldr	r0, [r3, r5, lsl #2]
  40:	e8bd4070 	pop	{r4, r5, r6, lr}
  44:	eafffffe 	b	0 <ioctl>
			44: R_ARM_JUMP24	ioctl
  48:	ebfffffe 	bl	0 <hi_mpi_mcf_set_grp_attr>
			48: R_ARM_CALL	mpi_mcf_check_grp_id.part.0
  4c:	e3500000 	cmp	r0, #0
  50:	18bd8070 	popne	{r4, r5, r6, pc}
  54:	eaffffed 	b	10 <hi_mpi_mcf_set_grp_attr+0x10>
  58:	ebfffffe 	bl	0 <hi_mpi_mcf_set_grp_attr>
			58: R_ARM_CALL	mpi_mcf_check_null_ptr.part.1
  5c:	e3500000 	cmp	r0, #0
  60:	18bd8070 	popne	{r4, r5, r6, pc}
  64:	eaffffeb 	b	18 <hi_mpi_mcf_set_grp_attr+0x18>
  68:	00000028 	.word	0x00000028
			68: R_ARM_REL32	.data.g_mcf_grp_fd

Disassembly of section .text.hi_mpi_mcf_get_grp_attr:

00000000 <hi_mpi_mcf_get_grp_attr>:
   0:	e92d4070 	push	{r4, r5, r6, lr}
   4:	e2505000 	subs	r5, r0, #0
   8:	e1a04001 	mov	r4, r1
   c:	1a00000d 	bne	48 <hi_mpi_mcf_get_grp_attr+0x48>
  10:	e3540000 	cmp	r4, #0
  14:	0a00000f 	beq	58 <hi_mpi_mcf_get_grp_attr+0x58>
  18:	e1a00005 	mov	r0, r5
  1c:	ebfffffe 	bl	0 <hi_mpi_mcf_get_grp_attr>
			1c: R_ARM_CALL	mpi_mcf_check_grp_open
  20:	e3500000 	cmp	r0, #0
  24:	18bd8070 	popne	{r4, r5, r6, pc}
  28:	e59f3038 	ldr	r3, [pc, #56]	; 68 <hi_mpi_mcf_get_grp_attr+0x68>
  2c:	e3001c08 	movw	r1, #3080	; 0xc08
  30:	e3481078 	movt	r1, #32888	; 0x8078
  34:	e1a02004 	mov	r2, r4
  38:	e08f3003 	add	r3, pc, r3
  3c:	e7930105 	ldr	r0, [r3, r5, lsl #2]
  40:	e8bd4070 	pop	{r4, r5, r6, lr}
  44:	eafffffe 	b	0 <ioctl>
			44: R_ARM_JUMP24	ioctl
  48:	ebfffffe 	bl	0 <hi_mpi_mcf_get_grp_attr>
			48: R_ARM_CALL	mpi_mcf_check_grp_id.part.0
  4c:	e3500000 	cmp	r0, #0
  50:	18bd8070 	popne	{r4, r5, r6, pc}
  54:	eaffffed 	b	10 <hi_mpi_mcf_get_grp_attr+0x10>
  58:	ebfffffe 	bl	0 <hi_mpi_mcf_get_grp_attr>
			58: R_ARM_CALL	mpi_mcf_check_null_ptr.part.1
  5c:	e3500000 	cmp	r0, #0
  60:	18bd8070 	popne	{r4, r5, r6, pc}
  64:	eaffffeb 	b	18 <hi_mpi_mcf_get_grp_attr+0x18>
  68:	00000028 	.word	0x00000028
			68: R_ARM_REL32	.data.g_mcf_grp_fd

Disassembly of section .text.hi_mpi_mcf_set_alg_param:

00000000 <hi_mpi_mcf_set_alg_param>:
   0:	e92d4070 	push	{r4, r5, r6, lr}
   4:	e2505000 	subs	r5, r0, #0
   8:	e1a04001 	mov	r4, r1
   c:	1a00000d 	bne	48 <hi_mpi_mcf_set_alg_param+0x48>
  10:	e3540000 	cmp	r4, #0
  14:	0a00000f 	beq	58 <hi_mpi_mcf_set_alg_param+0x58>
  18:	e1a00005 	mov	r0, r5
  1c:	ebfffffe 	bl	0 <hi_mpi_mcf_set_alg_param>
			1c: R_ARM_CALL	mpi_mcf_check_grp_open
  20:	e3500000 	cmp	r0, #0
  24:	18bd8070 	popne	{r4, r5, r6, pc}
  28:	e59f3038 	ldr	r3, [pc, #56]	; 68 <hi_mpi_mcf_set_alg_param+0x68>
  2c:	e3001c0b 	movw	r1, #3083	; 0xc0b
  30:	e3441102 	movt	r1, #16642	; 0x4102
  34:	e1a02004 	mov	r2, r4
  38:	e08f3003 	add	r3, pc, r3
  3c:	e7930105 	ldr	r0, [r3, r5, lsl #2]
  40:	e8bd4070 	pop	{r4, r5, r6, lr}
  44:	eafffffe 	b	0 <ioctl>
			44: R_ARM_JUMP24	ioctl
  48:	ebfffffe 	bl	0 <hi_mpi_mcf_set_alg_param>
			48: R_ARM_CALL	mpi_mcf_check_grp_id.part.0
  4c:	e3500000 	cmp	r0, #0
  50:	18bd8070 	popne	{r4, r5, r6, pc}
  54:	eaffffed 	b	10 <hi_mpi_mcf_set_alg_param+0x10>
  58:	ebfffffe 	bl	0 <hi_mpi_mcf_set_alg_param>
			58: R_ARM_CALL	mpi_mcf_check_null_ptr.part.1
  5c:	e3500000 	cmp	r0, #0
  60:	18bd8070 	popne	{r4, r5, r6, pc}
  64:	eaffffeb 	b	18 <hi_mpi_mcf_set_alg_param+0x18>
  68:	00000028 	.word	0x00000028
			68: R_ARM_REL32	.data.g_mcf_grp_fd

Disassembly of section .text.hi_mpi_mcf_get_alg_param:

00000000 <hi_mpi_mcf_get_alg_param>:
   0:	e92d4070 	push	{r4, r5, r6, lr}
   4:	e2505000 	subs	r5, r0, #0
   8:	e1a04001 	mov	r4, r1
   c:	1a00000d 	bne	48 <hi_mpi_mcf_get_alg_param+0x48>
  10:	e3540000 	cmp	r4, #0
  14:	0a00000f 	beq	58 <hi_mpi_mcf_get_alg_param+0x58>
  18:	e1a00005 	mov	r0, r5
  1c:	ebfffffe 	bl	0 <hi_mpi_mcf_get_alg_param>
			1c: R_ARM_CALL	mpi_mcf_check_grp_open
  20:	e3500000 	cmp	r0, #0
  24:	18bd8070 	popne	{r4, r5, r6, pc}
  28:	e59f3038 	ldr	r3, [pc, #56]	; 68 <hi_mpi_mcf_get_alg_param+0x68>
  2c:	e3001c0c 	movw	r1, #3084	; 0xc0c
  30:	e3481102 	movt	r1, #33026	; 0x8102
  34:	e1a02004 	mov	r2, r4
  38:	e08f3003 	add	r3, pc, r3
  3c:	e7930105 	ldr	r0, [r3, r5, lsl #2]
  40:	e8bd4070 	pop	{r4, r5, r6, lr}
  44:	eafffffe 	b	0 <ioctl>
			44: R_ARM_JUMP24	ioctl
  48:	ebfffffe 	bl	0 <hi_mpi_mcf_get_alg_param>
			48: R_ARM_CALL	mpi_mcf_check_grp_id.part.0
  4c:	e3500000 	cmp	r0, #0
  50:	18bd8070 	popne	{r4, r5, r6, pc}
  54:	eaffffed 	b	10 <hi_mpi_mcf_get_alg_param+0x10>
  58:	ebfffffe 	bl	0 <hi_mpi_mcf_get_alg_param>
			58: R_ARM_CALL	mpi_mcf_check_null_ptr.part.1
  5c:	e3500000 	cmp	r0, #0
  60:	18bd8070 	popne	{r4, r5, r6, pc}
  64:	eaffffeb 	b	18 <hi_mpi_mcf_get_alg_param+0x18>
  68:	00000028 	.word	0x00000028
			68: R_ARM_REL32	.data.g_mcf_grp_fd

Disassembly of section .text.hi_mpi_mcf_enable_chn:

00000000 <hi_mpi_mcf_enable_chn>:
   0:	e92d4070 	push	{r4, r5, r6, lr}
   4:	e2506000 	subs	r6, r0, #0
   8:	e59f5098 	ldr	r5, [pc, #152]	; a8 <hi_mpi_mcf_enable_chn+0xa8>
   c:	e24dd008 	sub	sp, sp, #8
  10:	e1a04001 	mov	r4, r1
  14:	e08f5005 	add	r5, pc, r5
  18:	1a000008 	bne	40 <hi_mpi_mcf_enable_chn+0x40>
  1c:	e3540000 	cmp	r4, #0
  20:	1a000012 	bne	70 <hi_mpi_mcf_enable_chn+0x70>
  24:	e1a01004 	mov	r1, r4
  28:	e1a00006 	mov	r0, r6
  2c:	ebfffffe 	bl	0 <hi_mpi_mcf_enable_chn>
			2c: R_ARM_CALL	mpi_mcf_check_chn_open
  30:	e3500000 	cmp	r0, #0
  34:	0a000006 	beq	54 <hi_mpi_mcf_enable_chn+0x54>
  38:	e28dd008 	add	sp, sp, #8
  3c:	e8bd8070 	pop	{r4, r5, r6, pc}
  40:	ebfffffe 	bl	0 <hi_mpi_mcf_enable_chn>
			40: R_ARM_CALL	mpi_mcf_check_grp_id.part.0
  44:	e3500000 	cmp	r0, #0
  48:	0afffff3 	beq	1c <hi_mpi_mcf_enable_chn+0x1c>
  4c:	e28dd008 	add	sp, sp, #8
  50:	e8bd8070 	pop	{r4, r5, r6, pc}
  54:	e59f3050 	ldr	r3, [pc, #80]	; ac <hi_mpi_mcf_enable_chn+0xac>
  58:	e3001c09 	movw	r1, #3081	; 0xc09
  5c:	e08f3003 	add	r3, pc, r3
  60:	e7930106 	ldr	r0, [r3, r6, lsl #2]
  64:	e28dd008 	add	sp, sp, #8
  68:	e8bd4070 	pop	{r4, r5, r6, lr}
  6c:	eafffffe 	b	0 <ioctl>
			6c: R_ARM_JUMP24	ioctl
  70:	e59f1038 	ldr	r1, [pc, #56]	; b0 <hi_mpi_mcf_enable_chn+0xb0>
  74:	e3a03086 	mov	r3, #134	; 0x86
  78:	e59f2034 	ldr	r2, [pc, #52]	; b4 <hi_mpi_mcf_enable_chn+0xb4>
  7c:	e7950001 	ldr	r0, [r5, r1]
  80:	e59f1030 	ldr	r1, [pc, #48]	; b8 <hi_mpi_mcf_enable_chn+0xb8>
  84:	e08f2002 	add	r2, pc, r2
  88:	e08f1001 	add	r1, pc, r1
  8c:	e5900000 	ldr	r0, [r0]
  90:	e58d4000 	str	r4, [sp]
  94:	ebfffffe 	bl	0 <fprintf>
			94: R_ARM_CALL	fprintf
  98:	e3080002 	movw	r0, #32770	; 0x8002
  9c:	e34a003d 	movt	r0, #41021	; 0xa03d
  a0:	e28dd008 	add	sp, sp, #8
  a4:	e8bd8070 	pop	{r4, r5, r6, pc}
  a8:	0000008c 	.word	0x0000008c
			a8: R_ARM_GOTPC	_GLOBAL_OFFSET_TABLE_
  ac:	00000048 	.word	0x00000048
			ac: R_ARM_REL32	.data.g_mcf_chn_fd
  b0:	00000000 	.word	0x00000000
			b0: R_ARM_GOT32	stderr
  b4:	00000028 	.word	0x00000028
			b4: R_ARM_REL32	.rodata.__FUNCTION__.10229
  b8:	00000028 	.word	0x00000028
			b8: R_ARM_REL32	.LC5

Disassembly of section .text.hi_mpi_mcf_disable_chn:

00000000 <hi_mpi_mcf_disable_chn>:
   0:	e92d4070 	push	{r4, r5, r6, lr}
   4:	e2506000 	subs	r6, r0, #0
   8:	e59f5098 	ldr	r5, [pc, #152]	; a8 <hi_mpi_mcf_disable_chn+0xa8>
   c:	e24dd008 	sub	sp, sp, #8
  10:	e1a04001 	mov	r4, r1
  14:	e08f5005 	add	r5, pc, r5
  18:	1a000008 	bne	40 <hi_mpi_mcf_disable_chn+0x40>
  1c:	e3540000 	cmp	r4, #0
  20:	1a000012 	bne	70 <hi_mpi_mcf_disable_chn+0x70>
  24:	e1a01004 	mov	r1, r4
  28:	e1a00006 	mov	r0, r6
  2c:	ebfffffe 	bl	0 <hi_mpi_mcf_disable_chn>
			2c: R_ARM_CALL	mpi_mcf_check_chn_open
  30:	e3500000 	cmp	r0, #0
  34:	0a000006 	beq	54 <hi_mpi_mcf_disable_chn+0x54>
  38:	e28dd008 	add	sp, sp, #8
  3c:	e8bd8070 	pop	{r4, r5, r6, pc}
  40:	ebfffffe 	bl	0 <hi_mpi_mcf_disable_chn>
			40: R_ARM_CALL	mpi_mcf_check_grp_id.part.0
  44:	e3500000 	cmp	r0, #0
  48:	0afffff3 	beq	1c <hi_mpi_mcf_disable_chn+0x1c>
  4c:	e28dd008 	add	sp, sp, #8
  50:	e8bd8070 	pop	{r4, r5, r6, pc}
  54:	e59f3050 	ldr	r3, [pc, #80]	; ac <hi_mpi_mcf_disable_chn+0xac>
  58:	e3001c0a 	movw	r1, #3082	; 0xc0a
  5c:	e08f3003 	add	r3, pc, r3
  60:	e7930106 	ldr	r0, [r3, r6, lsl #2]
  64:	e28dd008 	add	sp, sp, #8
  68:	e8bd4070 	pop	{r4, r5, r6, lr}
  6c:	eafffffe 	b	0 <ioctl>
			6c: R_ARM_JUMP24	ioctl
  70:	e59f1038 	ldr	r1, [pc, #56]	; b0 <hi_mpi_mcf_disable_chn+0xb0>
  74:	e3a03086 	mov	r3, #134	; 0x86
  78:	e59f2034 	ldr	r2, [pc, #52]	; b4 <hi_mpi_mcf_disable_chn+0xb4>
  7c:	e7950001 	ldr	r0, [r5, r1]
  80:	e59f1030 	ldr	r1, [pc, #48]	; b8 <hi_mpi_mcf_disable_chn+0xb8>
  84:	e08f2002 	add	r2, pc, r2
  88:	e08f1001 	add	r1, pc, r1
  8c:	e5900000 	ldr	r0, [r0]
  90:	e58d4000 	str	r4, [sp]
  94:	ebfffffe 	bl	0 <fprintf>
			94: R_ARM_CALL	fprintf
  98:	e3080002 	movw	r0, #32770	; 0x8002
  9c:	e34a003d 	movt	r0, #41021	; 0xa03d
  a0:	e28dd008 	add	sp, sp, #8
  a4:	e8bd8070 	pop	{r4, r5, r6, pc}
  a8:	0000008c 	.word	0x0000008c
			a8: R_ARM_GOTPC	_GLOBAL_OFFSET_TABLE_
  ac:	00000048 	.word	0x00000048
			ac: R_ARM_REL32	.data.g_mcf_chn_fd
  b0:	00000000 	.word	0x00000000
			b0: R_ARM_GOT32	stderr
  b4:	00000028 	.word	0x00000028
			b4: R_ARM_REL32	.rodata.__FUNCTION__.10229
  b8:	00000028 	.word	0x00000028
			b8: R_ARM_REL32	.LC5

Disassembly of section .text.hi_mpi_mcf_close_fd:

00000000 <hi_mpi_mcf_close_fd>:
   0:	e92d4070 	push	{r4, r5, r6, lr}
   4:	e59f5104 	ldr	r5, [pc, #260]	; 110 <hi_mpi_mcf_close_fd+0x110>
   8:	e59f4104 	ldr	r4, [pc, #260]	; 114 <hi_mpi_mcf_close_fd+0x114>
   c:	e08f5005 	add	r5, pc, r5
  10:	e08f4004 	add	r4, pc, r4
  14:	e1a00005 	mov	r0, r5
  18:	ebfffffe 	bl	0 <pthread_mutex_lock>
			18: R_ARM_CALL	pthread_mutex_lock
  1c:	e5940000 	ldr	r0, [r4]
  20:	e3500000 	cmp	r0, #0
  24:	ba000004 	blt	3c <hi_mpi_mcf_close_fd+0x3c>
  28:	ebfffffe 	bl	0 <close>
			28: R_ARM_CALL	close
  2c:	e3500000 	cmp	r0, #0
  30:	1a000010 	bne	78 <hi_mpi_mcf_close_fd+0x78>
  34:	e3e03000 	mvn	r3, #0
  38:	e5843000 	str	r3, [r4]
  3c:	e59f50d4 	ldr	r5, [pc, #212]	; 118 <hi_mpi_mcf_close_fd+0x118>
  40:	e08f5005 	add	r5, pc, r5
  44:	e5950000 	ldr	r0, [r5]
  48:	e3500000 	cmp	r0, #0
  4c:	ba00001c 	blt	c4 <hi_mpi_mcf_close_fd+0xc4>
  50:	ebfffffe 	bl	0 <close>
			50: R_ARM_CALL	close
  54:	e2504000 	subs	r4, r0, #0
  58:	1a00001e 	bne	d8 <hi_mpi_mcf_close_fd+0xd8>
  5c:	e59f00b8 	ldr	r0, [pc, #184]	; 11c <hi_mpi_mcf_close_fd+0x11c>
  60:	e3e03000 	mvn	r3, #0
  64:	e5853000 	str	r3, [r5]
  68:	e08f0000 	add	r0, pc, r0
  6c:	ebfffffe 	bl	0 <pthread_mutex_unlock>
			6c: R_ARM_CALL	pthread_mutex_unlock
  70:	e1a00004 	mov	r0, r4
  74:	e8bd8070 	pop	{r4, r5, r6, pc}
  78:	e59f40a0 	ldr	r4, [pc, #160]	; 120 <hi_mpi_mcf_close_fd+0x120>
  7c:	e59f00a0 	ldr	r0, [pc, #160]	; 124 <hi_mpi_mcf_close_fd+0x124>
  80:	e08f4004 	add	r4, pc, r4
  84:	e08f0000 	add	r0, pc, r0
  88:	ebfffffe 	bl	0 <perror>
			88: R_ARM_CALL	perror
  8c:	e5940000 	ldr	r0, [r4]
  90:	e3500000 	cmp	r0, #0
  94:	ba000018 	blt	fc <hi_mpi_mcf_close_fd+0xfc>
  98:	ebfffffe 	bl	0 <close>
			98: R_ARM_CALL	close
  9c:	e3500000 	cmp	r0, #0
  a0:	1a00000c 	bne	d8 <hi_mpi_mcf_close_fd+0xd8>
  a4:	e3e03000 	mvn	r3, #0
  a8:	e1a00005 	mov	r0, r5
  ac:	e5843000 	str	r3, [r4]
  b0:	e3084012 	movw	r4, #32786	; 0x8012
  b4:	e34a403d 	movt	r4, #41021	; 0xa03d
  b8:	ebfffffe 	bl	0 <pthread_mutex_unlock>
			b8: R_ARM_CALL	pthread_mutex_unlock
  bc:	e1a00004 	mov	r0, r4
  c0:	e8bd8070 	pop	{r4, r5, r6, pc}
  c4:	e59f005c 	ldr	r0, [pc, #92]	; 128 <hi_mpi_mcf_close_fd+0x128>
  c8:	e3a04000 	mov	r4, #0
  cc:	e08f0000 	add	r0, pc, r0
  d0:	ebfffffe 	bl	0 <pthread_mutex_unlock>
			d0: R_ARM_CALL	pthread_mutex_unlock
  d4:	eaffffe5 	b	70 <hi_mpi_mcf_close_fd+0x70>
  d8:	e59f004c 	ldr	r0, [pc, #76]	; 12c <hi_mpi_mcf_close_fd+0x12c>
  dc:	e3084012 	movw	r4, #32786	; 0x8012
  e0:	e34a403d 	movt	r4, #41021	; 0xa03d
  e4:	e08f0000 	add	r0, pc, r0
  e8:	ebfffffe 	bl	0 <perror>
			e8: R_ARM_CALL	perror
  ec:	e59f003c 	ldr	r0, [pc, #60]	; 130 <hi_mpi_mcf_close_fd+0x130>
  f0:	e08f0000 	add	r0, pc, r0
  f4:	ebfffffe 	bl	0 <pthread_mutex_unlock>
			f4: R_ARM_CALL	pthread_mutex_unlock
  f8:	eaffffdc 	b	70 <hi_mpi_mcf_close_fd+0x70>
  fc:	e1a00005 	mov	r0, r5
 100:	e3084012 	movw	r4, #32786	; 0x8012
 104:	e34a403d 	movt	r4, #41021	; 0xa03d
 108:	ebfffffe 	bl	0 <pthread_mutex_unlock>
			108: R_ARM_CALL	pthread_mutex_unlock
 10c:	eaffffd7 	b	70 <hi_mpi_mcf_close_fd+0x70>
 110:	000000fc 	.word	0x000000fc
			110: R_ARM_REL32	.bss.g_mcf_mutex
 114:	000000fc 	.word	0x000000fc
			114: R_ARM_REL32	.data.g_mcf_chn_fd
 118:	000000d0 	.word	0x000000d0
			118: R_ARM_REL32	.data.g_mcf_grp_fd
 11c:	000000ac 	.word	0x000000ac
			11c: R_ARM_REL32	.bss.g_mcf_mutex
 120:	00000098 	.word	0x00000098
			120: R_ARM_REL32	.data.g_mcf_grp_fd
 124:	00000098 	.word	0x00000098
			124: R_ARM_REL32	.LC6
 128:	00000054 	.word	0x00000054
			128: R_ARM_REL32	.bss.g_mcf_mutex
 12c:	00000040 	.word	0x00000040
			12c: R_ARM_REL32	.LC7
 130:	00000038 	.word	0x00000038
			130: R_ARM_REL32	.bss.g_mcf_mutex
